
import gregtech.api.GTValues;
recipemap('large_chemical_reactor').recipeBuilder()
        .fluidInputs(fluid('laponergium_solution') * 12000)
        .inputs(ore('dustYttrium') * 10)
        .inputs(ore('dustSaturnite') * 7)
        .fluidOutputs(fluid('lossless_superconductive_field') * 1000)
        .duration(340).EUt(GTValues.VA[GTValues.IV]).buildAndRegister()
                 
recipemap('large_chemical_reactor').recipeBuilder()
        .fluidInputs(fluid('oxidized_watz_mud') * 1000)
        .inputs(ore('dustLapotron'))
        .inputs(ore('dustEnergium'))
        .fluidOutputs(fluid('laponergium_solution') * 1000)
        .duration(1280).EUt(GTValues.VA[GTValues.HV]).buildAndRegister()

recipemap('large_chemical_reactor').recipeBuilder()
        .fluidInputs(fluid('watz') * 1000)
        .fluidInputs(fluid('oxygen') * 16000)
        .fluidOutputs(fluid('oxidized_watz_mud') * 1000)
        .duration(720).EUt(GTValues.VA[GTValues.MV]).buildAndRegister()

recipemap('large_chemical_reactor').recipeBuilder()
        .fluidInputs(fluid('poisoned_hive_field') * 1000)
        .fluidInputs(fluid('blood') * 7000)
        .fluidOutputs(fluid('irritated_hive_field') * 1000)
        .duration(720).EUt(GTValues.VA[GTValues.MV]).buildAndRegister()

recipemap('large_chemical_reactor').recipeBuilder()
        .inputs(ore('dustAssimilatedScraps') * 10)
        .fluidInputs(fluid('aqua_regia') * 7000)
        .fluidInputs(fluid('hydrochloric_acid') * 14000)
        .fluidInputs(fluid('liquid_death') * 14000)
        .fluidOutputs(fluid('irritated_hive_field') * 1000)
        .duration(720).EUt(GTValues.VA[GTValues.MV]).buildAndRegister()

recipemap('large_chemical_reactor').recipeBuilder()
        .fluidInputs(fluid('laponergium_solution') * 7000)
        .fluidInputs(fluid('irritated_hive_field') * 1000)
        .fluidOutputs(fluid('electrified_hive_field') * 1000)
        .chancedOutput(metaitem('dustLapotron'), 10, 20)
        .duration(24000).EUt(GTValues.VA[GTValues.IV]).buildAndRegister()

recipemap('large_chemical_reactor').recipeBuilder()
        .fluidInputs(fluid('blaze') * 14000)
        .fluidInputs(fluid('cortisol') * 16000)
        .notConsumable(ore('stickTitanium') * 2)
        .inputs(ore('dustArsenic') * 9)
        .inputs(ore('dustLead') * 7)
        .fluidInputs(fluid('electrified_hive_field') * 1000)
        .fluidOutputs(fluid('tortured_hive_field') * 1000)
        .chancedOutput(metaitem('dustArsenic'), 10, 20)
        .duration(800).EUt(GTValues.VA[GTValues.HV]).buildAndRegister()

recipemap('large_chemical_reactor').recipeBuilder()
        .fluidInputs(fluid('tortured_hive_field') * 1000)
        .fluidInputs(fluid('blaze') * 14000)
        .inputs(ore('dustRedPhosphorus') * 12)
        .inputs(item('thermalfoundation:material', 1024) * 9)
        .notConsumable(ore('gemVolcanic'))
        .fluidInputs(fluid('infernal_lava') * 16000)
        .fluidOutputs(fluid('scorching_hive_field') * 1000)
        .chancedOutput(metaitem('dustRedPhosphorus'), 10, 20)
        .duration(2400).EUt(GTValues.VA[GTValues.HV]).buildAndRegister()

recipemap('large_chemical_reactor').recipeBuilder()
        .fluidInputs(fluid('testosterone') * 16000)
       .fluidInputs(fluid('lossless_superconductive_field') * 1000)
        .inputs(ore('dustAssimilatedScraps') * 9)
        .notConsumable(ore('dustAdvancedPolypeptide') * 4)
        .fluidInputs(fluid('scorching_hive_field') * 16000)
        .fluidOutputs(fluid('contained_hive_field') * 1000)
        .duration(800).EUt(GTValues.VA[GTValues.HV]).buildAndRegister()

recipemap('large_chemical_reactor').recipeBuilder()
        .fluidInputs(fluid('lava') * 16000)
        .fluidInputs(fluid('blaze') * 1000)
        .inputs(ore('dustSmallBlaze') * 9)
        .inputs(item('thermalfoundation:material', 1024) * 9)
        .notConsumable(ore('gemVolcanic'))
        .fluidOutputs(fluid('infernal_lava') * 1000)
        .duration(800).EUt(GTValues.VA[GTValues.HV]).buildAndRegister()

        recipemap('large_chemical_reactor').recipeBuilder()
        .fluidInputs(fluid('scorching_hive_field') * 100)
        .fluidInputs(fluid('gtfo_hot_frying_oil') * 1000)
        .inputs(ore('dustSmallSalt') * 9)
        .inputs(ore('dustBlackPepper') * 7)
        .fluidOutputs(fluid('gourmet_hive_field') * 1000)
        .duration(800).EUt(GTValues.VA[GTValues.HV]).buildAndRegister()