recipemap('assembly_line').recipeBuilder()
        .stationResearch(b -> b.researchStack(item('gtaurora:data.elementary')).CWUt(12))
        .inputs(ore('foilAntiferrachloricDineutroniumDraconiumSchrabidate') * 4)
        .inputs(ore('screwAntineutronium') * 12)
        .inputs(item('gregtech:meta_item_1', 532) * 4)
        .inputs(item('gregtech:meta_item_1', 531) * 4)
        .inputs(item('gregtech:meta_item_1', 601) * 24)
        .inputs(item('gregtech:meta_item_1', 600) * 24)
        .inputs(item('gregtech:optical_pipe_normal') * 4)
        .inputs(item('gtaurora:circuit_board.optical'))
        .inputs(ore('wireFinePositronChargedEuroschidiumAlloy') * 6)
        .fluidInputs(fluid('schrabidium_based_sold_alloy') * 148 )
        .outputs(item('gtaurora:circuit.optical_processor'))
        .duration(800).EUt(8388608).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .inputs(ore('dustNeutronium') * 6)
        .inputs(ore('dustSmallLithiumChloride') * 6)
        .fluidInputs(fluid('sas3') * 120 )
        .fluidInputs(fluid('amat') * 120 )
        .fluidInputs(fluid('draconium') * 150 )
        .fluidOutputs(fluid('antiferrachloric_dineutronium_draconium_schrabidate') * 270 )
        .duration(120).EUt(2097152).buildAndRegister()


recipemap('assembly_line').recipeBuilder()
        .stationResearch(b -> b.researchStack(item('gtaurora:data.nuclear')).CWUt(12))
        .inputs(ore('foilStableNeoveline') * 4)
        .inputs(ore('screwAntineutronium') * 12)
        .inputs(item('gtaurora:schrabidium_neutronium_processing_module_component') * 2)
        .inputs(item('gregtech:meta_item_1', 532) * 4)
        .inputs(item('gregtech:meta_item_1', 531) * 4)
        .inputs(item('gregtech:meta_item_1', 601) * 24)
        .inputs(item('gregtech:meta_item_1', 600) * 24)
        .inputs(item('gregtech:optical_pipe_normal') * 12)
        .inputs(item('gtaurora:circuit_board.optical'))
        .inputs(ore('wireFinePositronChargedEuroschidiumAlloy') * 6)
        .fluidInputs(fluid('schrabidium_based_sold_alloy') * 148 )
        .outputs(item('gtaurora:circuit.optical_assembly'))
        .duration(800).EUt(8388608).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .inputs(item('hbm:powder_radspice') * 6)
        .fluidInputs(fluid('supercoolant') * 12000 )
        .fluidInputs(fluid('amat') * 120 )
        .fluidInputs(fluid('draconium') * 150 )
        .fluidOutputs(fluid('stable_neoveline') * 270 )
        .duration(120).EUt(8388608).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .inputs(item('gregtech:meta_item_1', 386))
        .inputs(item('gregtech:meta_item_1', 599))
        .fluidInputs(fluid('draconium') * 150 )
        .outputs(item('gtaurora:circuit_board.optical'))
        .duration(120).EUt(8388608).buildAndRegister()

recipemap('assembly_line').recipeBuilder()
        .stationResearch(b -> b.researchStack(item('gtaurora:data.nuclear')).CWUt(12))
        .inputs(ore('foilStableNeoveline') * 12)
        .inputs(ore('screwNaquadahAlloy') * 12)
        .inputs(item('gtaurora:schrabidium_neutronium_processing_module_component') * 4)
        .inputs(item('gregtech:meta_item_1', 532) * 4)
        .inputs(item('gregtech:meta_item_1', 531) * 4)
        .inputs(item('gregtech:meta_item_1', 601) * 24)
        .inputs(item('gregtech:meta_item_1', 600) * 24)
        .inputs(item('gregtech:meta_item_1', 599) * 4)
        .inputs(item('gregtech:optical_pipe_normal') * 12)
        .inputs(item('gtaurora:circuit_board.optical'))
        .inputs(ore('wireFineStableNeoveline') * 6)
        .fluidInputs(fluid('schrabidium_based_sold_alloy') * 148 )
        .outputs(item('gtaurora:circuit.optical_array'))
        .duration(800).EUt(8388608).buildAndRegister()

recipemap('assembly_line').recipeBuilder()
        .stationResearch(b -> b.researchStack(item('gtaurora:data.nuclear')).CWUt(12))
        .inputs(ore('foilStableNeoveline') * 64)
        .inputs(ore('screwNaquadahAlloy') * 12)
        .inputs(ore('wireFinePositronChargedAntineutronium') * 64)
        .inputs(ore('plateDraconium') * 64)
        .inputs(item('gtaurora:schrabidium_neutronium_processing_module_component') * 4)
        .inputs(item('gregtech:meta_item_1', 532) * 64)
        .inputs(item('gregtech:meta_item_1', 531) * 64)
        .inputs(item('gregtech:meta_item_1', 601) * 64)
        .inputs(item('gregtech:meta_item_1', 600) * 32)
        .inputs(item('gregtech:meta_item_1', 599) * 12)
        .inputs(item('gregtech:optical_pipe_normal') * 12)
        .inputs(item('gtaurora:circuit_board.optical'))
        .inputs(ore('wireFineStableNeoveline') * 6)
        .fluidInputs(fluid('schrabidium_based_sold_alloy') * 148 )
        .outputs(item('gtaurora:circuit.optical_mainframe'))
        .duration(800).EUt(8388608).buildAndRegister()