oreDict.add("circuitZpm", item('gt_aurora:hyperconducting_antischrabidic_circuit'))
oreDict.add("circuitMv", item('gt_aurora:botathaumahaemic_sentient_hivemind_cell'))
oreDict.add("circuitHv", item('gt_aurora:botathaumahaemic_sentient_hivemind'))
oreDict.add("circuitUv", item('gt_aurora:hyperconducting_antischrabidic_assembly'))
oreDict.add("circuitUhv", item('gt_aurora:hyperconducting_antischrabidic_computer'))
oreDict.add("circuitUev", item('gt_aurora:hyperconducting_antischrabidic_mainframe'))