oreDict.add("circuitZpm", item('gt_aurora:hyperconducting_antischrabidic_circuit'))
oreDict.add("circuitMv", item('gt_aurora:botathaumahaemic_sentient_hivemind_cell'))
oreDict.add("circuitHv", item('gt_aurora:botathaumahaemic_sentient_hivemind'))
oreDict.add("circuitUv", item('gt_aurora:hyperconducting_antischrabidic_assembly'))
oreDict.add("circuitUhv", item('gt_aurora:hyperconducting_antischrabidic_computer'))
oreDict.add("circuitUev", item('gt_aurora:hyperconducting_antischrabidic_mainframe'))
oreDict.add("circuitUv", item('gtaurora:circuit.exotic_capsule'))
oreDict.add("circuitUev", item('gtaurora:circuit.exotic_assemblyanim'))
oreDict.add("circuitOpv", item('gtaurora:circuit.exotic_mainframe'))
oreDict.add("ingotWorkersAlloy", item('gregtech:meta_ingot', 32125))
oreDict.add("circuitOpv", item('gtaurora:circuit.exotic_mainframe'))
oreDict.add("dustWorkersAlloy", item('gregtech:meta_dust', 32125))
oreDict.add("plateWorkersAlloy", item('gregtech:meta_plate', 32125))
oreDict.add("circuitUv", item('gtaurora:circuit.optical_processor'))
oreDict.add("circuitUhv", item('gtaurora:circuit.optical_assembly'))
oreDict.add("circuitUev", item('gtaurora:circuit.optical_array'))
oreDict.add("circuitUiv", item('gtaurora:circuit.optical_mainframe'))