oreDict.add("circuitZpm", item('gt_aurora:hyperconducting_antischrabidic_circuit'))
oreDict.add("circuitMv", item('gt_aurora:botathaumahaemic_sentient_hivemind_cell'))
oreDict.add("circuitHv", item('gt_aurora:botathaumahaemic_sentient_hivemind'))
oreDict.add("circuitUv", item('gt_aurora:hyperconducting_antischrabidic_assembly'))
oreDict.add("circuitUhv", item('gt_aurora:hyperconducting_antischrabidic_computer'))
oreDict.add("circuitUev", item('gt_aurora:hyperconducting_antischrabidic_mainframe'))
oreDict.add("circuitUv", item('gtaurora:circuit.exotic_capsule'))
oreDict.add("circuitUev", item('gtaurora:circuit.exotic_assemblyanim'))
oreDict.add("circuitOpv", item('gtaurora:circuit.exotic_mainframe'))
oreDict.add("ingotWorkersAlloy", item('gregtech:meta_ingot', 32125))
oreDict.add("circuitOpv", item('gtaurora:circuit.exotic_mainframe'))
oreDict.add("dustWorkersAlloy", item('gregtech:meta_dust', 32125))
oreDict.add("plateWorkersAlloy", item('gregtech:meta_plate', 32125))
oreDict.add("circuitUv", item('gtaurora:circuit.optical_processor'))
oreDict.add("circuitUhv", item('gtaurora:circuit.optical_assembly'))
oreDict.add("circuitUev", item('gtaurora:circuit.optical_array'))
oreDict.add("circuitUiv", item('gtaurora:circuit.optical_mainframe'))
oreDict.add("ingotAnyPlastic", item('gregtech:meta_plate', 1012))
oreDict.add("ingotAnyPlastic", item('gregtech:meta_plate', 1012))
oreDict.add("circuitUhv", item('gtaurora:circuit.amped_wetware_processor'))
oreDict.add("circuitUev", item('gtaurora:circuit.amped_wetware_assembly'))
oreDict.add("circuitUiv", item('gtaurora:circuit.amped_wetware_array'))
oreDict.add("circuitUxv", item('gtaurora:circuit.amped_wetware_mainframe'))
oreDict.add("oc:materialTransistor", item('gregtech:meta_item_1', 518))
oreDict.add("oc:circuitChip1", item('gregtech:meta_item_1', 626))
oreDict.add("oc:circuitChip2", item('gregtech:meta_item_1', 623))
oreDict.add("oc:circuitChip3", item('gregtech:meta_item_1', 625))
oreDict.add("wireCopper", item('gregtech:meta_wire_fine', 25))
oreDict.add("wireElectrum", metaitem('wireFineElectrum'))
oreDict.add("wireAluminium", metaitem('wireFineAluminium'))
oreDict.add("ingotAluminum", metaitem('ingotAluminium'))
oreDict.add("plateAluminum", metaitem('plateAluminium'))
oreDict.add("wireTungsten", metaitem('wireGtSingleTungsten'))
oreDict.add("wireSteel", metaitem('wireFineSteel'))
oreDict.add("wireBrass", metaitem('wireFineZinc'))
oreDict.add("electronTube", item('gregtech:meta_item_1', 516))
oreDict.add("wireAluminum", metaitem('wireFineAluminium'))
oreDict.add("dustAluminum", metaitem('dustAluminium'))
oreDict.add("plateAluminum", metaitem('plateAluminium'))
oreDict.add("ingotThauminite", item('thaumicbases:thauminite_ingot'))
oreDict.add("dustEnergium", item('gregtech:meta_item_1', 491))