ore('ingotTitanium').remove(item('hbm:ingot_titanium'))
ore('Titanium').remove(item('hbm:ingot_titanium'))


import gregtech.api.metatileentity.multiblock.CleanroomType

recipemap('assembler').recipeBuilder()
         .inputs(ore('dustTin'))
         .inputs(item('gregtech:meta_dust', 320))
         .outputs(item('enderio:item_material', 22))
         .duration(200).EUt(120).buildAndRegister()

recipemap('centrifuge').recipeBuilder()
        .inputs(item('bloodmagic:component:8'))
        .chancedOutput(item('embers:shard_ember'), 500, 500)
        .duration(200).EUt(120).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .inputs(ore('dustDiamond'), ore('dustLithium') * 2)
        .fluidInputs(fluid('ammonia') * 100)
        .outputs(item('libvulpes:productgem'))
        .duration(200).EUt(200).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .fluidInputs(fluid('liquid_air') * 100)
        .fluidInputs(fluid('ammonia') * 250)
        .fluidOutputs(fluid('rocketfuel') * 100)
        .duration(400).EUt(200).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .inputs(item('gregtech:meta_ingot', 277) * 2 )
        .fluidInputs(fluid('oxygen') * 250 )
        .outputs(item('enderutilities:enderpart') * 2 )
        .duration(400).EUt(60).buildAndRegister()

recipemap('assembler').recipeBuilder()
         .inputs(ore('ingotSiliconeRubber') * 4 )
         .fluidInputs(fluid('soldering_alloy') * 72 )
         .inputs(ore('ingotOsmium') * 1 )
         .inputs(ore('ingotIridium') * 2 )
         .outputs(item('appliedenergistics2:material', 52) * 16 )
         .duration(200).EUt(7500).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(ore('blockGlass') * 2 )
        .inputs(ore('gemFluix') * 4 )
        .fluidInputs(fluid('radon') * 100)
        .outputs(item('appliedenergistics2:part', 16) * 32 )
        .duration(200).EUt(200).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
         .inputs(ore('dustKanthal') * 2 )
         .fluidInputs(fluid('oxygen') * 200 )
         .inputs(ore('ingotSteel') * 2 )
         .outputs(item('gregtech:meta_dust', 214) * 16)
         .duration(600).EUt(120).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(ore('blockGlass') * 2 )
        .inputs(ore('gemFluix') * 4 )
        .fluidInputs(fluid('fluorine') * 130)
        .outputs(item('appliedenergistics2:part', 16) * 32 )
        .duration(200).EUt(200).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .inputs(item('gregtech:meta_ingot', 32003) * 2 )
        .fluidInputs(fluid('aschrab') * 250 )
        .outputs(item('gregtech:meta_ingot', 32012) * 2 )
        .duration(400).EUt(2097152).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .inputs(ore('itemBinderComposite') * 12)
        .fluidInputs(fluid('sas3') * 120 )
        .fluidInputs(fluid('soldering_alloy') * 120 )
        .fluidInputs(fluid('darmstadtium') * 150 )
        .fluidOutputs(fluid('schrabidium_based_sold_alloy') * 250 )
        .duration(400).EUt(600000).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .inputs(ore('ingotNeutronium') * 12)
        .fluidInputs(fluid('sas3') * 120 )
        .fluidInputs(fluid('amat') * 120 )
        .fluidInputs(fluid('darmstadtium') * 150 )
        .fluidOutputs(fluid('antineutronium') * 270 )
        .duration(400).EUt(620000).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .inputs(ore('ingotSchrabidium') * 12)
        .inputs(item('hbm:powder_ice') * 4)
        .fluidInputs(fluid('iridium') * 120 )
        .fluidInputs(fluid('palladium') * 120 )
        .fluidOutputs(fluid('irschridium') * 270 )
        .duration(400).EUt(2048).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .inputs(ore('dustSaltpeter'))
        .inputs(ore('rodBlizz') * 4)
        .fluidInputs(fluid('distilled_water') * 120 )
        .fluidInputs(fluid('water') * 120 )
        .fluidOutputs(fluid('coolant') * 40 )
        .duration(400).EUt(510).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(ore('wireFineAluminium'), ore('dustLithium') * 2)
        .inputs(ore('componentDiode'), item('gregtech:meta_item_1', 402 ) * 2)
        .fluidInputs(fluid('soldering_alloy') * 72)
        .outputs(item('hbm:circuit_raw'))
        .duration(200).EUt(120).buildAndRegister()

recipemap('fusion_reactor').recipeBuilder()
        .fluidInputs(fluid('germanium') * 250)
        .fluidInputs(fluid('plutonium') * 500 )
        .fluidOutputs(fluid('schrabidium') * 150)
        .duration(400).EUt(62000).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .inputs(ore('dustRedstone') * 8)
        .inputs(ore('ingotCopper') * 16)
        .fluidInputs(fluid('oxygen') * 120 )
        .fluidInputs(fluid('nitrogen') * 120 )
        .outputs(item('hbm:ingot_red_copper') * 4)
        .duration(400).EUt(120).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .inputs(item('hbm:ingot_red_copper') * 8)
        .inputs(ore('ingotSteel') * 16)
        .fluidInputs(fluid('oxygen') * 120 )
        .fluidInputs(fluid('nitrogen') * 120 )
        .outputs(item('hbm:ingot_advanced_alloy') * 4)
        .duration(600).EUt(120).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(item('gregtech:meta_item_1', 498) * 2)
        .inputs(ore('plateDenseAluminium') * 2)
        .inputs(ore('plateSteel') * 2)
        .fluidInputs(fluid('steel') * 120)
        .outputs(item('hbm:warhead_generic_small'))
        .duration(200).EUt(120).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(ore('wireFineAluminium') * 2)
        .inputs(ore('frameGtBlackSteel') * 12)
        .inputs(ore('plateSteel') * 24)
        .inputs(ore('circuitMv') * 4)
        .inputs(ore('componentDiode') * 4)
        .fluidInputs(fluid('steel') * 500)
        .outputs(item('hbm:launch_pad'))
        .duration(200).EUt(120).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(ore('plateSteel') * 2)
        .inputs(ore('plateAluminium') * 12)
        .inputs(item('gregtech:meta_item_1', 81))
        .inputs(ore('componentResistor') * 1)
        .inputs(ore('componentDiode') * 4)
        .fluidInputs(fluid('steel') * 200)
        .outputs(item('hbm:thruster_small'))
        .duration(200).EUt(120).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(ore('plateSteel') * 2)
        .inputs(ore('plateAluminium') * 4)
        .inputs(item('hbm:hull_big_aluminium') * 2)
        .inputs(ore('componentDiode') * 4)
        .inputs(item('hbm:thruster_small') * 2)
        .inputs(item('hbm:warhead_generic_small'))
        .inputs(item('hbm:circuit_targeting_tier1') * 2)
        .fluidInputs(fluid('aluminium') * 120)
        .outputs(item('hbm:missile_generic'))
        .duration(1200).EUt(120).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(ore('plateSteel') * 2)
        .inputs(ore('plateAluminium') * 12)
        .inputs(item('gregtech:meta_item_1', 81))
        .fluidInputs(fluid('steel') * 200)
        .outputs(item('hbm:fuel_tank_small') * 2)
        .duration(200).EUt(120).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .inputs(ore('ingotEuropium') * 6)
        .fluidInputs(fluid('amat') * 120 )
        .fluidInputs(fluid('aschrab') * 120 )
        .fluidOutputs(fluid('positron_charged_euroschidium_alloy') * 120 )
        .duration(400).EUt(620000).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .inputs(ore('dustSulfur') * 6)
        .fluidInputs(fluid('steam') * 500 )
        .fluidInputs(fluid('diesel') * 120 )
        .fluidOutputs(fluid('kerosene') * 240 )
        .duration(400).EUt(120).buildAndRegister()

recipemap('assembly_line').recipeBuilder()
        .inputs(ore('screwDarmstadtium') * 12)
        .inputs(ore('screwNaquadahAlloy') * 4)
        .inputs(item('gregtech:meta_item_1', 532) * 4)
        .inputs(item('gregtech:meta_item_1', 531) * 4)
        .inputs(item('gregtech:meta_item_1', 528) * 4)
        .inputs(item('gregtech:meta_item_1', 529) * 4)
        .inputs(ore('platePositronChargedEuroschidiumAlloy') * 12)
        .inputs(ore('wireFinePositronChargedEuroschidiumAlloy') * 6)
        .fluidInputs(fluid('schrabidium_based_sold_alloy') * 148 )
        .fluidInputs(fluid('polybenzimidazole') * 144 )
        .outputs(item('gt_aurora:hyperconducting_antischrabidic_circuit') * 2)
        .duration(800).EUt(524288).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(item('hbm:warhead_generic_medium'))
        .inputs(ore('plateDenseAluminium') * 2)
        .inputs(ore('dustRedPhosphorus') * 2)
        .fluidInputs(fluid('toluene') * 120)
        .outputs(item('hbm:warhead_incendiary_small'))
        .duration(200).EUt(120).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(item('hbm:warhead_generic_medium'))
        .inputs(item('hbm:pellet_cluster') * 2)
        .fluidInputs(fluid('steel') * 120)
        .outputs(item('hbm:warhead_cluster_small'))
        .duration(200).EUt(120).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(item('minecraft:tnt'))
        .inputs(ore('plateSteel') * 2)
        .fluidInputs(fluid('steel') * 120)
        .outputs(item('hbm:pellet_cluster') * 8)
        .duration(200).EUt(120).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(item('hbm:warhead_generic_medium'))
        .inputs(item('hbm:det_cord') * 8)
        .fluidInputs(fluid('aluminium') * 120)
        .outputs(item('hbm:warhead_buster_small'))
        .duration(200).EUt(120).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(ore('plateSteel') * 2)
        .inputs(ore('plateAluminium') * 4)
        .inputs(item('hbm:hull_big_aluminium') * 2)
        .inputs(ore('componentDiode') * 4)
        .inputs(item('hbm:thruster_small') * 2)
        .inputs(item('hbm:warhead_buster_small'))
        .inputs(item('hbm:circuit_targeting_tier1') * 2)
        .fluidInputs(fluid('aluminium') * 120)
        .outputs(item('hbm:missile_buster'))
        .duration(1200).EUt(120).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(ore('plateSteel') * 2)
        .inputs(ore('plateAluminium') * 4)
        .inputs(item('hbm:hull_big_aluminium') * 2)
        .inputs(ore('componentDiode') * 4)
        .inputs(item('hbm:thruster_small') * 2)
        .inputs(item('hbm:warhead_cluster_small'))
        .inputs(item('hbm:circuit_targeting_tier1') * 2)
        .fluidInputs(fluid('aluminium') * 120)
        .outputs(item('hbm:missile_cluster'))
        .duration(1200).EUt(120).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(ore('plateSteel') * 2)
        .inputs(ore('plateAluminium') * 4)
        .inputs(item('hbm:hull_big_aluminium') * 2)
        .inputs(ore('componentDiode') * 4)
        .inputs(item('hbm:thruster_small') * 2)
        .inputs(item('hbm:warhead_incendiary_small'))
        .inputs(item('hbm:circuit_targeting_tier1') * 2)
        .fluidInputs(fluid('aluminium') * 120)
        .outputs(item('hbm:missile_incendiary'))
        .duration(1200).EUt(120).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(item('gregtech:meta_item_1', 460) * 2)
        .inputs(ore('plateDenseStainlessSteel') * 2)
        .inputs(ore('plateSteel') * 12)
        .inputs(ore('screwStainlessSteel') * 2)
        .fluidInputs(fluid('silicone_rubber') * 120)
        .outputs(item('hbm:warhead_generic_medium'))
        .duration(200).EUt(500).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(ore('plateSteel') * 2)
        .inputs(ore('plateStainlessSteel') * 4)
        .inputs(ore('platePolyethylene') * 4)
        .inputs(ore('componentResistor') * 1)
        .inputs(ore('circuitLv') * 4)
        .fluidInputs(fluid('stainless_steel') * 200)
        .outputs(item('hbm:thruster_medium'))
        .duration(200).EUt(500).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(ore('plateStainlessSteel') * 2)
        .inputs(ore('plateBlackSteel') * 4)
        .inputs(ore('platePolyethylene') * 4)
        .inputs(ore('componentResistor') * 1)
        .inputs(ore('circuitLv') * 4)
        .fluidInputs(fluid('stainless_steel') * 200)
        .outputs(item('hbm:fuel_tank_medium'))
        .duration(200).EUt(500).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(item('hbm:warhead_generic_medium'))
        .inputs(ore('plateDenseAluminium') * 2)
        .inputs(ore('dustRedPhosphorus') * 2)
        .fluidInputs(fluid('glyceryl_trinitrate') * 120)
        .outputs(item('hbm:warhead_incendiary_medium'))
        .duration(200).EUt(500).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(item('hbm:warhead_generic_medium'))
        .inputs(item('hbm:det_charge') * 4)
        .fluidInputs(fluid('stainless_steel') * 120)
        .outputs(item('hbm:warhead_buster_medium'))
        .duration(200).EUt(500).buildAndRegister()

recipemap('cutter').recipeBuilder()
        .inputs(item('hbm:ingot_red_copper'))
        .fluidInputs(fluid('lubricant') * 122 )
        .outputs(item('hbm:wire_red_copper') * 8)
        .cleanroom(CleanroomType.CLEANROOM)
        .duration(450).EUt(120).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(item('hbm:warhead_generic_medium'))
        .inputs(item('hbm:det_cord') * 2)
        .inputs(item('hbm:pellet_cluster') * 4)
        .fluidInputs(fluid('stainless_steel') * 120)
        .outputs(item('hbm:warhead_cluster_medium'))
        .duration(200).EUt(500).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(ore('plateBlackSteel') * 2)
        .inputs(ore('plateStainlessSteel') * 4)
        .inputs(item('hbm:hull_big_aluminium') * 8)
        .inputs(item('hbm:thruster_medium') * 2)
        .inputs(item('hbm:warhead_generic_medium'))
        .inputs(item('hbm:circuit_targeting_tier2') * 2)
        .fluidInputs(fluid('stainless_steel') * 120)
        .outputs(item('hbm:missile_strong'))
        .duration(1200).EUt(120).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(ore('plateBlackSteel') * 2)
        .inputs(ore('plateStainlessSteel') * 4)
        .inputs(item('hbm:hull_big_aluminium') * 8)
        .inputs(item('hbm:thruster_medium') * 2)
        .inputs(item('hbm:warhead_incendiary_medium'))
        .inputs(item('hbm:circuit_targeting_tier2') * 2)
        .fluidInputs(fluid('stainless_steel') * 120)
        .outputs(item('hbm:missile_incendiary_strong'))
        .duration(1200).EUt(120).buildAndRegister()

recipemap('mixer').recipeBuilder()
        .inputs(ore('dustOsmium') * 6)
        .inputs(ore('dustPalladium') * 6)
        .inputs(ore('dustIridium') * 6)
        .outputs(item('gt_aurora:ultradense_powder'))
        .duration(400).EUt(2048).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(ore('plateAluminium') * 2)
        .inputs(item('hbm:circuit_raw') * 4)
        .inputs(ore('wireFineAluminium') * 4)
        .inputs(item('gregtech:meta_item_1', 521))
        .fluidInputs(fluid('tin') * 120)
        .outputs(item('hbm:circuit_aluminium') * 2)
        .duration(200).EUt(120).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(ore('plateAluminium') * 2)
        .inputs(ore('wireFineCopper') * 4)
        .inputs(item('gregtech:meta_item_1', 521))
        .inputs(item('hbm:circuit_aluminium') * 2)
        .fluidInputs(fluid('tin') * 120)
        .outputs(item('hbm:circuit_copper') * 2)
        .duration(200).EUt(120).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(ore('plateBlackSteel') * 2)
        .inputs(ore('plateStainlessSteel') * 4)
        .inputs(item('hbm:hull_big_aluminium') * 8)
        .inputs(item('hbm:thruster_medium') * 2)
        .inputs(item('hbm:warhead_cluster_medium'))
        .inputs(item('hbm:circuit_targeting_tier2') * 2)
        .fluidInputs(fluid('stainless_steel') * 120)
        .outputs(item('hbm:missile_cluster_strong'))
        .duration(1200).EUt(120).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(ore('plateBlackSteel') * 2)
        .inputs(ore('plateStainlessSteel') * 4)
        .inputs(item('hbm:hull_big_aluminium') * 8)
        .inputs(item('hbm:thruster_medium') * 2)
        .inputs(item('hbm:warhead_buster_medium'))
        .inputs(item('hbm:circuit_targeting_tier2') * 2)
        .fluidInputs(fluid('stainless_steel') * 120)
        .outputs(item('hbm:missile_buster_strong'))
        .duration(1200).EUt(120).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(ore('plateTitanium') * 2)
        .inputs(ore('plateStainlessSteel') * 12)
        .inputs(item('hbm:hull_big_aluminium') * 8)
        .inputs(item('hbm:thruster_medium') * 2)
        .inputs(item('hbm:warhead_cluster_medium'))
        .inputs(item('hbm:circuit_targeting_tier2') * 2)
        .fluidInputs(fluid('stainless_steel') * 120)
        .outputs(item('hbm:missile_cluster_strong'))
        .duration(1200).EUt(120).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(ore('plateTitanium') * 2)
        .inputs(ore('plateStainlessSteel') * 4)
        .inputs(item('hbm:hull_big_titanium') * 8)
        .inputs(item('hbm:thruster_large') * 2)
        .inputs(item('hbm:warhead_buster_large'))
        .inputs(item('hbm:circuit_targeting_tier3') * 2)
        .fluidInputs(fluid('polytetrafluoroethylene') * 120)
        .outputs(item('hbm:missile_drill'))
        .duration(1200).EUt(1200).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(ore('plateTitanium') * 2)
        .inputs(ore('plateStainlessSteel') * 4)
        .inputs(item('hbm:hull_big_titanium') * 8)
        .inputs(item('hbm:thruster_large') * 2)
        .inputs(item('hbm:fuel_tank_large') * 2)
        .inputs(item('hbm:warhead_generic_large'))
        .inputs(item('hbm:circuit_targeting_tier3') * 2)
        .fluidInputs(fluid('polytetrafluoroethylene') * 120)
        .outputs(item('hbm:missile_burst'))
        .duration(1200).EUt(1200).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(ore('plateTitanium') * 2)
        .inputs(ore('plateStainlessSteel') * 4)
        .inputs(item('hbm:hull_big_titanium') * 8)
        .inputs(item('hbm:thruster_large') * 2)
        .inputs(item('hbm:fuel_tank_large') * 2)
        .inputs(item('hbm:warhead_cluster_large'))
        .inputs(item('hbm:circuit_targeting_tier3') * 2)
        .fluidInputs(fluid('polytetrafluoroethylene') * 120)
        .outputs(item('hbm:missile_rain'))
        .duration(1200).EUt(1200).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(ore('plateTitanium') * 2)
        .inputs(ore('plateStainlessSteel') * 4)
        .inputs(item('hbm:hull_big_titanium') * 8)
        .inputs(item('hbm:thruster_large') * 2)
        .inputs(item('hbm:fuel_tank_large') * 2)
        .inputs(item('hbm:warhead_incendiary_large'))
        .inputs(item('hbm:circuit_targeting_tier3') * 2)
        .fluidInputs(fluid('polytetrafluoroethylene') * 120)
        .outputs(item('hbm:missile_inferno'))
        .duration(1200).EUt(1200).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(ore('plateTitanium') * 2)
        .inputs(ore('plateStainlessSteel') * 4)
        .inputs(item('hbm:hull_big_titanium') * 8)
        .inputs(item('hbm:thruster_large') * 2)
        .inputs(item('hbm:fuel_tank_large') * 2)
        .inputs(item('hbm:warhead_incendiary_large'))
        .inputs(item('hbm:circuit_targeting_tier3') * 2)
        .fluidInputs(fluid('polytetrafluoroethylene') * 120)
        .outputs(item('hbm:missile_inferno'))
        .duration(1200).EUt(1200).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(item('gregtech:meta_item_1', 460) * 12)
        .inputs(ore('plateDenseTitanium') * 2)
        .inputs(ore('plateSteel') * 24)
        .inputs(ore('screwStainlessSteel') * 2)
        .fluidInputs(fluid('polytetrafluoroethylene') * 120)
        .outputs(item('hbm:warhead_generic_large'))
        .duration(200).EUt(1024).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(ore('plateSteel') * 2)
        .inputs(ore('plateStainlessSteel') * 4)
        .inputs(item('hbm:hull_big_titanium') * 4)
        .inputs(ore('platePolyethylene') * 4)
        .inputs(ore('componentResistor') * 1)
        .inputs(ore('circuitMv') * 4)
        .fluidInputs(fluid('polytetrafluoroethylene') * 200)
        .outputs(item('hbm:thruster_large'))
        .duration(200).EUt(1024).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(ore('plateTitanium') * 2)
        .inputs(item('hbm:hull_big_aluminium') * 4)
        .inputs(ore('plateBlackSteel') * 4)
        .inputs(ore('platePolyethylene') * 4)
        .inputs(ore('componentResistor') * 1)
        .inputs(ore('circuitMv') * 4)
        .fluidInputs(fluid('polytetrafluoroethylene') * 200)
        .outputs(item('hbm:fuel_tank_large'))
        .duration(200).EUt(1024).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .inputs(ore('dustAstralStarmetal') * 6)
        .fluidInputs(fluid('plastic') * 500 )
        .fluidInputs(fluid('astralsorcery.liquidstarlight') * 120 )
        .fluidOutputs(fluid('polyastraethylene') * 240 )
        .duration(400).EUt(240).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(item('gregtech:meta_item_1', 386) * 3)
        .inputs(item('hbm:wire_schrabidium') * 2)
        .inputs(item('hbm:wire_schrabidium') * 2)
        .inputs(ore('dustNitanium') * 24)
        .inputs(ore('circuitUv'))
        .inputs(ore('screwDarmstadtium') * 2)
        .fluidInputs(fluid('polybenzimidazole') * 120)
        .outputs(item('gt_aurora:sparkschrabidic_epoxy_resin_sheet') * 2)
        .duration(200).EUt(60000).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .inputs(item('gt_aurora:sparkschrabidic_epoxy_resin_sheet') * 2)
        .fluidInputs(fluid('superschrabidium_board_reactant') * 120)
        .fluidInputs(fluid('supercoolant') * 20)
        .outputs(item('gt_aurora:sparkschrabidic_circuit_board') * 2)
        .duration(200).EUt(60000).buildAndRegister()