mods.tconstruct.melting.recipeBuilder()
    .input(ore('oreGarnierite'))
    .fluidOutput(fluid('nickel') * 144)
    .time(80)
    .register()

mods.tconstruct.melting.recipeBuilder()
    .input(ore('oreGalena'))
    .fluidOutput(fluid('lead') * 144)
    .time(80)
    .register()

mods.tconstruct.melting.recipeBuilder()
    .input(ore('oreChalcopyrite'))
    .fluidOutput(fluid('copper') * 144)
    .time(80)
    .register()

mods.tconstruct.melting.recipeBuilder()
    .input(ore('orePyrite'))
    .fluidOutput(fluid('iron') * 144)
    .time(80)
    .register()

mods.tconstruct.melting.recipeBuilder()
    .input(ore('oreMalachite'))
    .fluidOutput(fluid('copper') * 144)
    .time(80)
    .register()

mods.tconstruct.melting.recipeBuilder()
    .input(ore('oreCassiterite'))
    .fluidOutput(fluid('tin') * 144)
    .time(23)
    .register()

mods.tconstruct.melting.recipeBuilder()
    .input(ore('oreYellowLimonite'))
    .fluidOutput(fluid('iron') * 166)
    .time(80)
    .register()

mods.tconstruct.melting.recipeBuilder()
    .input(ore('oreBrownLimonite'))
    .fluidOutput(fluid('iron') * 166)
    .time(80)
    .register()

mods.tconstruct.melting.recipeBuilder()
    .input(ore('oreLead'))
    .fluidOutput(fluid('lead') * 122)
    .time(80)
    .register()

mods.tconstruct.melting.recipeBuilder()
    .input(ore('oreBasalticMineralSand'))
    .fluidOutput(fluid('iron') * 166)
    .time(80)
    .register()

mods.tconstruct.melting.recipeBuilder()
    .input(ore('oreGraniticMineralSand'))
    .fluidOutput(fluid('iron') * 144)
    .time(80)
    .register()

mods.tconstruct.melting.recipeBuilder()
    .input(ore('oreCobaltite'))
    .fluidOutput(fluid('cobalt') * 144)
    .time(80)
    .register()

mods.tconstruct.melting.recipeBuilder()
    .input(ore('oreNickel'))
    .fluidOutput(fluid('nickel') * 144)
    .time(23)
    .register()