
mods.thaumcraft.infusion_crafting.recipeBuilder()
    .researchKey('UNLOCKALCHEMY@3')
    .mainInput(ore('livingrock'))
    .output(item('botania:runealtar'))
    .aspect(aspect('terra') * 200)
    .aspect('herba', 150)
    .input(item('thaumicrestoration:item_shard'))
    .input(item('thaumcraft:mind:1'))
    .input(item('thaumcraft:metal_alchemical_advanced'))
    .input(item('thaumcraft:metal_alchemical_advanced'))
    .input(item('thaumicrestoration:item_ingot:4'))
    .instability(5)
    .register()

mods.thaumcraft.crucible.recipeBuilder()
    .researchKey('UNLOCKALCHEMY@3')
    .catalyst(item('minecraft:clay'))
    .output(item('embers:blend_caminite'))
    .aspect(aspect('machina') * 25)
    .aspect(aspect('auram') * 40)
    .register()

mods.thaumcraft.dust_trigger.triggerBuilder()
    .researchKey('UNLOCKALCHEMY@3')
    .target(block('thaumicadditions:mithrillium_block'))
    .output(item('botania:pool', 2))
    .register()

mods.thaumcraft.infusion_crafting.recipeBuilder()
    .researchKey('UNLOCKALCHEMY@3')
    .mainInput(ore('stoneMarble'))
    .output(item('astralsorcery:blockblackmarble'))
    .aspect(aspect('perditio') * 200)
    .aspect('praecantatio', 150)
    .input(item('bloodmagic:ritual_stone', 4))
    .input(item('thaumcraft:ingot', 1))
    .input(ore('nuggetMithrillium'))
    .input(item('thaumcraft:metal_alchemical_advanced'))
    .input(item('thaumicrestoration:item_ingot', 5))
    .instability(5)
    .register()

mods.thaumcraft.infusion_crafting.recipeBuilder()
    .researchKey('UNLOCKALCHEMY@3')
    .mainInput(ore('ingotThaumium'))
    .output(item('gregtech:meta_ingot', 32001))
    .aspect(aspect('perditio') * 200)
    .aspect('vitium', 150)
    .input(item('thaumcraft:curio'))
    .input(ore('ingotThaumiumPerditio'))
    .input(ore('nuggetMithrillium'))
    .instability(5)
    .register()

mods.thaumcraft.crucible.recipeBuilder()
    .researchKey('UNLOCKALCHEMY@3')
    .catalyst(item('thaumcraft:nugget', 9))
    .output(item('essentialcraft:gem_elemental'))
    .aspect(aspect('ignis') * 40)
    .register()

mods.thaumcraft.crucible.recipeBuilder()
    .researchKey('UNLOCKALCHEMY@3')
    .catalyst(item('thaumcraft:nugget', 9))
    .output(item('essentialcraft:gem_elemental', 1))
    .aspect(aspect('aqua') * 40)
    .register()

mods.thaumcraft.crucible.recipeBuilder()
    .researchKey('UNLOCKALCHEMY@3')
    .catalyst(item('thaumcraft:nugget', 9))
    .output(item('essentialcraft:gem_elemental', 2))
    .aspect(aspect('terra') * 40)
    .register()

mods.thaumcraft.crucible.recipeBuilder()
    .researchKey('UNLOCKALCHEMY@3')
    .catalyst(item('thaumcraft:nugget', 9))
    .output(item('essentialcraft:gem_elemental', 3))
    .aspect(aspect('aer') * 40)
    .register()

mods.thaumcraft.infusion_crafting.recipeBuilder()
    .researchKey('UNLOCKALCHEMY@3')
    .mainInput(item('bloodarsenal:base_item', 5))
    .output(item('gt_aurora:botathaumahaemic_sentient_hivemind_cell'))
    .aspect(aspect('perditio') * 120)
    .aspect('mortuus', 50)
    .input(item('bloodmagic:demon_crystal'))
    .input(ore('ingotThaumiumPerditio'))
    .input(item('bloodarsenal:base_item', 4))
    .input(item('bloodmagic:slate', 1))
    .input(ore('ingotManasteel'))
    .instability(20)
    .register()