recipemap('chemical_reactor').recipeBuilder()
        .fluidInputs(fluid('redstone') * 100)
        .inputs(ore('dustRedstone') * 32)
        .inputs(ore('dustLithium') * 4)
        .fluidOutputs(fluid('redstone_reactant') * 640)
        .duration(80).EUt(500).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .fluidInputs(fluid('redstone') * 100)
        .fluidInputs(fluid('redstone_reactant') * 10)
        .fluidOutputs(fluid('thermally_expanded_redstone_solution') * 320)
        .duration(420).EUt(500).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .fluidInputs(fluid('thermally_expanded_redstone_solution') * 100)
        .fluidInputs(fluid('distilled_water') * 100)
        .inputs(ore('dustQuartz') * 3)
        .inputs(ore('dustCertusQuartz') * 4)
        .fluidOutputs(fluid('highly_impure_fluix_slurry') * 100)
        .duration(920).EUt(500).buildAndRegister()

recipemap('centrifuge').recipeBuilder()
        .fluidInputs(fluid('highly_impure_fluix_slurry') * 100)
        .fluidOutputs(fluid('pure_fluix_slurry') * 100)
        .duration(320).EUt(500).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .fluidInputs(fluid('pure_fluix_slurry') * 100)
        .fluidInputs(fluid('indium_concentrate') * 100)
        .outputs(item('gregtech:meta_dust', 32161))
        .duration(80).EUt(500).buildAndRegister()

recipemap('autoclave').recipeBuilder()
        .inputs(ore('dustGemGradeFluixDust'))
        .outputs(item('gregtech:meta_gem', 32141))
        .duration(80).EUt(500).buildAndRegister()