mods.pneumaticcraft.refinery.removeAll()
mods.pneumaticcraft.thermopneumatic_processing_plant.removeAll()

recipemap('assembler').recipeBuilder()
        .fluidInputs(fluid('iron_compressed') * 144)
        .inputs(ore('plateIronCompressed') * 2)
        .inputs(ore('screwIronCompressed') * 4)
        .inputs(ore('dustRedstone') * 4)
        .outputs(item('pneumaticcraft:pressure_tube') * 2)
        .duration(80).EUt(12).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .fluidInputs(fluid('iron_compressed') * 144)
        .inputs(ore('plateIronCompressed') * 2)
        .inputs(ore('componentDiode') * 2)
        .inputs(ore('wireFineCopper') * 4)
        .outputs(item('pneumaticcraft:pressure_gauge'))
        .duration(80).EUt(12).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .fluidInputs(fluid('iron_compressed') * 144)
        .inputs(ore('ringIronCompressed'))
        .inputs(ore('wireGtSingleCopper') * 2)
        .inputs(ore('plateIronCompressed') * 4)
        .inputs(ore('roundIronCompressed') * 2)
        .outputs(item('pneumaticcraft:air_canister'))
        .duration(80).EUt(12).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .fluidInputs(fluid('tin') * 144)
        .inputs(item('pneumaticcraft:turbine_blade') * 4)
        .inputs(ore('roundIronCompressed'))
        .inputs(ore('ringIronCompressed'))
        .outputs(item('pneumaticcraft:turbine_rotor'))
        .duration(80).EUt(32).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .fluidInputs(fluid('iron_compressed') * 144)
        .inputs(ore('plateIronCompressed') * 24)
        .inputs(ore('stickIronCompressed') * 16)
        .inputs(ore('frameGtSteel'))
        .outputs(item('pneumaticcraft:pressure_chamber_wall') * 8)
        .duration(80).EUt(128).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .fluidInputs(fluid('glass') * 144)
        .inputs(item('pneumaticcraft:pressure_chamber_wall') * 4)
        .outputs(item('pneumaticcraft:pressure_chamber_glass') * 4)
        .duration(80).EUt(32).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .fluidInputs(fluid('glass') * 144)
        .inputs(item('pneumaticcraft:pressure_chamber_wall'))
        .inputs(item('pneumaticcraft:pressure_gauge'))
        .inputs(ore('ringIronCompressed') * 2)
        .outputs(item('pneumaticcraft:pressure_chamber_valve'))
        .duration(80).EUt(32).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .fluidInputs(fluid('glass') * 144)
        .inputs(item('pneumaticcraft:pressure_chamber_wall'))
        .inputs(ore('circuitLv'))
        .inputs(ore('ringCompressedIron') * 2)
        .inputs(ore('roundIronCompressed'))
        .outputs(item('pneumaticcraft:pressure_chamber_interface'))
        .duration(80).EUt(32).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .fluidInputs(fluid('glass') * 144)
        .inputs(ore('plateIronCompressed') * 4)
        .inputs(ore('circuitMv') * 2)
        .inputs(item('pneumaticcraft:printed_circuit_board'))
        .inputs(item('pneumaticcraft:turbine_rotor') * 4)
        .inputs(ore('wireFineAluminium') * 2)
        .inputs(ore('roundIronCompressed'))
        .outputs(item('pneumaticcraft:drone'))
        .duration(80).EUt(32).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .fluidInputs(fluid('glass') * 144)
        .inputs(ore('plateIronCompressed') * 4)
        .inputs(ore('circuitMv') * 2)
        .inputs(item('pneumaticcraft:printed_circuit_board'))
        .inputs(item('pneumaticcraft:turbine_rotor') * 4)
        .inputs(item('gregtech:machine', 8561))
        .inputs(ore('wireFineAluminium') * 2)
        .inputs(ore('roundIronCompressed'))
        .outputs(item('pneumaticcraft:harvesting_drone'))
        .duration(80).EUt(32).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .fluidInputs(fluid('glass') * 144)
        .inputs(ore('plateIronCompressed') * 4)
        .inputs(ore('circuitMv') * 2)
        .inputs(item('pneumaticcraft:printed_circuit_board'))
        .inputs(item('pneumaticcraft:turbine_rotor') * 4)
        .inputs(ore('wireFineAluminium') * 2)
        .inputs(ore('roundIronCompressed'))
        .outputs(item('pneumaticcraft:logistic_drone'))
        .duration(80).EUt(32).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .fluidInputs(fluid('nitric_acid') * 100)
        .fluidInputs(fluid('sulfuric_copper_solution') * 100)
        .fluidInputs(fluid('hydrochloric_acid') * 100)
        .fluidOutputs(fluid('etchacid') * 100)
        .duration(180).EUt(32).buildAndRegister()

recipemap('implosion_compressor').recipeBuilder()
        .inputs(ore('dustIron') * 2)
        .inputs(ore('dustGunpowder'))
        .inputs(ore('dustBlaze'))
        .outputs(metaitem('dustIronCompressed') * 2)
        .duration(180).EUt(240).buildAndRegister()
