
recipemap('assembler').recipeBuilder()
        .inputs(ore('oc:dataCard3'))
        .inputs(ore('skullEnderResonator'))
        .inputs(ore('paperBlack') * 32)
        .fluidInputs(fluid('enderium') * 288 )
        .outputs(item('rftools:shape_card'))
        .duration(2400).EUt(2048).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(item('gregtech:machine', 986))
        .inputs(item('forestry:thermionic_tubes', 4))
        .inputs(ore('dustRedAlloy') * 32)
        .fluidInputs(fluid('soldering_alloy') * 144 )
        .outputs(item('rftools:machine_frame'))
        .duration(640).EUt(16).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(item('gregtech:meta_item_1', 402))
        .inputs(ore('dustRedAlloy') * 3)
        .inputs(ore('wireGtSingleCopper') * 9)
        .fluidInputs(fluid('gold') * 144 )
        .outputs(item('rftoolscontrol:card_base'))
        .duration(320).EUt(16).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(item('rftoolscontrol:card_base'))
        .inputs(ore('dustGold') * 3)
        .fluidInputs(fluid('glass') * 144)
        .outputs(item('rftoolscontrol:crafting_card'))
        .duration(120).EUt(16).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(item('rftoolscontrol:card_base'))
        .inputs(ore('plateSilicon') * 3)
        .inputs(ore('componentTransistor') * 2)
        .fluidInputs(fluid('glass') * 144)
        .outputs(item('rftoolscontrol:ram_chip'))
        .duration(120).EUt(16).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(item('rftoolscontrol:card_base') * 2)
        .inputs(ore('dustSulfur') * 3)
        .inputs(ore('componentDiode') * 2)
        .fluidInputs(fluid('glass') * 144)
        .outputs(item('rftoolscontrol:network_card'))
        .duration(120).EUt(16).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(item('rftoolscontrol:card_base'))
        .inputs(ore('dustRedstone') * 3)
        .inputs(ore('componentDiode') * 2)
        .fluidInputs(fluid('glass') * 144)
        .outputs(item('rftoolscontrol:graphics_card'))
        .duration(120).EUt(16).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(item('rftools:shape_card'))
        .inputs(ore('plateSilicon') * 3)
        .inputs(ore('componentTransistor') * 2)
        .fluidInputs(fluid('fluxed_electrum') * 16384)
        .outputs(item('rftools:shape_card', 2))
        .duration(120).EUt(2048).buildAndRegister()