recipemap('assembler').recipeBuilder()
        .inputs(ore('gearBrass') * 16)
        .inputs(item('gregtech:meta_item_1', 602))
        .inputs(ore('cableGtSingleCopper') * 12)
        .inputs(ore('circuitMv'))
        .outputs(item('gendustry:power_module'))
        .duration(1240).EUt(120).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(ore('plateBrass') * 16)
        .inputs(item('gregtech:meta_item_1', 602))
        .inputs(ore('cableGtSingleCopper') * 12)
        .inputs(ore('circuitMv'))
        .outputs(item('gendustry:genetics_processor'))
        .duration(2400).EUt(340).buildAndRegister()