
// listen to gregtech material event
mods.gregtech.materialEvent {
 materialBuilder(32001,'essentia_boosted_thaumium')
    .ingot().fluid()
    .color(0x9800eb).iconSet('METALLIC')
    .flags('generate_plate', 'generate_rod', 'generate_frame')
    .cableProperties(128, 1, 0, true)
.build()

 materialBuilder(32003,'antineutronium')
    .ingot().fluid()
    .color(0x8D91A9).iconSet('DULL')
    .flags('generate_plate', 'generate_rod', 'generate_frame', 'generate_dense', 'generate_rotor')
.build()

 materialBuilder(32005,'schrabidium')
    .ingot().fluid()
    .ore()
    .element("Schrabidium")
    .color(0x00f2ff).iconSet('METALLIC')
    .flags('generate_plate', 'generate_rod', 'generate_frame', 'generate_foil', 'generate_fine_wire', 'generate_lens','generate_rod')
    .cableProperties(8192, 1, 0, true)
    .fluidPipeProperties(1420, 10, false)
.build()

materialBuilder(32004,'thaumahaemic_alloy')
    .ingot().fluid()
    .color(0x9e0505).iconSet('METALLIC')
    .flags('generate_plate', 'generate_rod', 'generate_frame', 'generate_foil', 'generate_fine_wire','generate_rod')
    .cableProperties(512, 1, 0, true)
    .fluidPipeProperties(1420, 10, false)
.build()

materialBuilder(32020,'botathaumic_alloy')
    .ingot().fluid()
    .color(0x00d94c).iconSet('SHINY')
    .flags('generate_plate', 'generate_rod', 'generate_foil', 'generate_fine_wire','generate_rod')
    .cableProperties(256, 1, 0, true)
.build()

materialBuilder(32012,'positron_charged_antineutronium')
    .ingot().fluid()
    .color(0x00d94c).iconSet('MAGNETIC')
    .flags('generate_plate', 'generate_rod', 'generate_foil', 'generate_fine_wire','generate_rod')
    .cableProperties(256, 1, 0, true)
    .fluidPipeProperties(1420, 10, false)
.build()

 materialBuilder(32123,'schrabidium_based_sold_alloy')
    .ingot().fluid()
    .color(0xcceded).iconSet('DULL')
.build()

 materialBuilder(32424,'hypoconductive')
    .ingot().fluid()
    .color(0xd97ef2).iconSet('shiny')
    .flags('generate_plate', 'generate_rod', 'generate_foil', 'generate_fine_wire','generate_rod')
    .cableProperties(2097152, 1, 0, true)

 materialBuilder(32124,'irschridium')
    .ingot().fluid()
    .components(material('schrabidium'), material('iridium'))
    .color(0xf0fffb).iconSet('dull')
    .flags('generate_plate', 'generate_rod', 'generate_foil', 'generate_fine_wire','generate_rod')
    .cableProperties(2097152, 1, 200, false)
.build()

 materialBuilder(32524,'germanium')
    .ingot().fluid()
    .color(0x636363).iconSet('dull')
    .flags('generate_plate', 'generate_rod', 'generate_foil', 'generate_fine_wire','generate_rod')
    .cableProperties(120, 1, 20, false)
.build()

 materialBuilder(32128,'positron_charged_euroschidium_alloy')
    .ingot().fluid()
    .ore()
    .color(0x00eeff).iconSet('MAGNETIC')
    .flags('generate_plate', 'generate_rod', 'generate_frame', 'generate_foil', 'generate_fine_wire', 'generate_lens','generate_rod')
    .cableProperties(8192, 1, 0, false)
.build()

 materialBuilder(32526, 'neutron_star_matter')
        .liquid(fluidBuilder())
        .color(0xd6e9ff)
.build()

 materialBuilder(32523, 'hot_quark_mess')
        .liquid(fluidBuilder())
        .color(0x9effcf)
.build()

 materialBuilder(31523, 'quark_mess')
        .liquid(fluidBuilder())
        .color(0x9effcf)
.build()

 materialBuilder(32543, 'essence_of_the_void')
        .liquid(fluidBuilder())
        .color(0x190042)
.build()

    materialBuilder(32623, 'up_quark')
        .liquid(fluidBuilder())
        .color(0x9effcf)
.build()

    materialBuilder(32223, 'down_quark')
        .liquid(fluidBuilder())
        .color(0x00b3ff)
.build()

    materialBuilder(32423, 'strange_quark')
        .liquid(fluidBuilder())
        .color(0x00ff2a)
.build()

    materialBuilder(32089, 'charm_quark')
        .liquid(fluidBuilder())
        .color(0x6ff00)
.build()

    materialBuilder(32189, 'aspectus_quark')
        .liquid(fluidBuilder())
        .color(0x25004a)
.build()

    materialBuilder(32105, 'supercoolant')
        .liquid(fluidBuilder())
        .color(0x78d9ff)
.build()

    materialBuilder(32229, 'temporal_reactant')
        .liquid(fluidBuilder())
        .color(0xa8000b)
.build()

    materialBuilder(32129, 'superschrabidium_board_reactant')
        .liquid(fluidBuilder())
        .color(0x00fffb)
.build()

 materialBuilder(32106,'void')
    .ingot().fluid()
    .color(0x25004a).iconSet('DULL')
    .element("Voidmetal")
    .flags('generate_plate', 'generate_rod', 'generate_frame', 'generate_dense', 'generate_rotor')
.build()

 materialBuilder(32070, 'polyastraethylene')
        .liquid(fluidBuilder())
        .color(0xf4e3ff)
.build()
}