
// listen to gregtech material event
mods.gregtech.materialEvent {
 materialBuilder(32001,'essentia_boosted_thaumium')
    .ingot().fluid()
    .color(0x9800eb).iconSet('METALLIC')
    .flags('generate_plate', 'generate_rod', 'generate_frame')
    .cableProperties(128, 1, 0, true)
.build()

 materialBuilder(32003,'antineutronium')
    .ingot().fluid()
    .element("Neutronium")
    .color(0x8D91A9).iconSet('DULL')
    .flags('generate_plate', 'generate_rod', 'generate_frame', 'generate_dense', 'generate_rotor')
.build()

 materialBuilder(32005,'schrabidium')
    .ingot().fluid()
    .ore()
    .blastTemp(5600, "HIGH")
    .element("Schrabidium")
    .color(0x00f2ff).iconSet('METALLIC')
    .flags('generate_plate', 'generate_rod', 'generate_frame', 'generate_foil', 'generate_fine_wire', 'generate_lens','generate_rod')
    .cableProperties(8192, 1, 0, true)
    .fluidPipeProperties(1420, 10, false)
.build()

materialBuilder(32004,'thaumahaemic_alloy')
    .ingot().fluid()
    .color(0x9e0505).iconSet('METALLIC')
    .flags('generate_plate', 'generate_rod', 'generate_frame', 'generate_foil', 'generate_fine_wire','generate_rod')
    .cableProperties(512, 1, 0, true)
    .fluidPipeProperties(1420, 10, false)
.build()

materialBuilder(32020,'botathaumic_alloy')
    .ingot().fluid()
    .color(0x00d94c).iconSet('SHINY')
    .flags('generate_plate', 'generate_rod', 'generate_foil', 'generate_fine_wire','generate_rod')
    .cableProperties(256, 1, 0, true)
.build()

materialBuilder(32012,'positron_charged_antineutronium')
    .ingot().fluid()
    .color(0x00d94c).iconSet('MAGNETIC')
    .flags('generate_plate', 'generate_rod', 'generate_foil', 'generate_fine_wire','generate_rod')
    .cableProperties(256, 1, 0, true)
    .fluidPipeProperties(1420, 10, false)
.build()

 materialBuilder(32123,'schrabidium_based_sold_alloy')
    .ingot().fluid()
    .color(0xcceded).iconSet('DULL')
.build()

 materialBuilder(32424,'hypoconductive')
    .ingot().fluid()
    .color(0xd97ef2).iconSet('shiny')
    .flags('generate_plate', 'generate_rod', 'generate_foil', 'generate_fine_wire','generate_rod')
    .cableProperties(2097152, 1, 0, true)

 materialBuilder(32124,'irschridium')
    .ingot().fluid()
    .blastTemp(5600, "HIGHER")
    .components(material('schrabidium'), material('iridium'))
    .color(0xf0fffb).iconSet('dull')
    .flags('generate_plate', 'generate_rod', 'generate_foil', 'generate_fine_wire','generate_rod')
    .cableProperties(2097152, 1, 200, false)
.build()

 materialBuilder(32524,'germanium')
    .ingot().fluid()
    .blastTemp(2700, "MID")
    .color(0x636363).iconSet('dull')
    .ore()
    .flags('generate_plate', 'generate_rod', 'generate_foil', 'generate_fine_wire','generate_rod')
    .cableProperties(120, 1, 20, false)
.build()

 materialBuilder(32128,'positron_charged_euroschidium_alloy')
    .ingot().fluid()
    .color(0x00eeff).iconSet('MAGNETIC')
    .flags('generate_plate', 'generate_rod', 'generate_frame', 'generate_foil', 'generate_fine_wire', 'generate_lens','generate_rod')
    .cableProperties(8192, 1, 0, false)
.build()

 materialBuilder(32526, 'neutron_star_matter')
        .liquid(fluidBuilder())
        .color(0xd6e9ff)
.build()

 materialBuilder(32523, 'hot_quark_mess')
        .liquid(fluidBuilder())
        .color(0x9effcf)
.build()

 materialBuilder(31523, 'quark_mess')
        .liquid(fluidBuilder())
        .color(0x9effcf)
.build()

 materialBuilder(32543, 'essence_of_the_void')
        .liquid(fluidBuilder())
        .color(0x190042)
.build()

    materialBuilder(32623, 'up_quark')
        .liquid(fluidBuilder())
        .color(0x9effcf)
.build()

    materialBuilder(32223, 'down_quark')
        .liquid(fluidBuilder())
        .color(0x00b3ff)
.build()

    materialBuilder(32423, 'strange_quark')
        .liquid(fluidBuilder())
        .color(0x00ff2a)
.build()

    materialBuilder(32089, 'charm_quark')
        .liquid(fluidBuilder())
        .color(0x6ff00)
.build()

    materialBuilder(32189, 'aspectus_quark')
        .liquid(fluidBuilder())
        .color(0x25004a)
.build()

    materialBuilder(32105, 'supercoolant')
        .liquid(fluidBuilder())
        .color(0x78d9ff)
.build()

    materialBuilder(32229, 'temporal_reactant')
        .liquid(fluidBuilder())
        .color(0xa8000b)
.build()

    materialBuilder(32129, 'superschrabidium_board_reactant')
        .liquid(fluidBuilder())
        .color(0x00fffb)
.build()

 materialBuilder(32106,'void')
    .ingot().fluid()
    .blastTemp(2700, "MID")
    .color(0x25004a).iconSet('DULL')
    .element("Voidmetal")
    .flags('generate_plate', 'generate_rod', 'generate_frame', 'generate_dense', 'generate_rotor')
.build()

 materialBuilder(32070, 'polyastraethylene')
        .liquid(fluidBuilder())
        .color(0xf4e3ff)
.build()

 materialBuilder(32107, 'vitalium')
    .ingot().fluid()
    .color(0xc41849).iconSet('METALLIC')
    .flags('generate_plate', 'generate_rod', 'generate_frame', 'generate_dense', 'generate_rotor')
    .toolStats(toolBuilder()
            .unbreakable() // makes the tools unbreakable (default false)
            .magnetic() // Blocks mined with a tool of this materials go straight into the player inventory (default false)
    )
.build()

 materialBuilder(32108, 'dark_steel')
    .ingot().fluid()
    .blastTemp(2700, "MID")
    .components(material('iron'), material('carbon'))
    .color(0x2e2e2e).iconSet('METALLIC')
    .flags('generate_plate', 'generate_rod', 'generate_frame', 'generate_dense', 'generate_rotor')
.build()

 materialBuilder(32109, 'electrical_steel')
    .ingot().fluid()
    .blastTemp(2700, "MID")
    .components(material('iron'), material('graphite'))
    .color(0x0b0b0).iconSet('METALLIC')
    .flags('generate_plate', 'generate_rod', 'generate_frame', 'generate_dense', 'generate_rotor')
.build()

 materialBuilder(32110, 'energetic_alloy')
    .ingot().fluid()
    .blastTemp(2700, "MID")
    .components(material('redstone'), material('gold'), material('ender_pearl'))
    .color(0xfa9600).iconSet('METALLIC')
    .flags('generate_plate', 'generate_rod', 'generate_frame', 'generate_dense', 'generate_rotor')
.build()

 materialBuilder(32111, 'draconium')
    .ingot().fluid().ore()
    .blastTemp(10800, "HIGHEST")
    .element("Draconium")
    .color(0x9800eb).iconSet('SHINY')
    .flags('generate_plate', 'generate_rod', 'generate_frame', 'generate_dense', 'generate_rotor', "no_smelting", )
.build()

 materialBuilder(32071, 'low_enriched_draconic_solution')
        .components(material('draconium'), material('neptunium'), material('neutronium'))
        .liquid(fluidBuilder())
        .color(0xf4e3ff)
    .build()

 materialBuilder(32072, 'enriched_draconic_solution')
        .liquid(fluidBuilder())
        .components(material('draconium'), material('neptunium'))
        .color(0x9800eb)
.build()

 materialBuilder(32112, 'energetic_silver')
    .ingot().fluid()
    .blastTemp(2700, "MID")
    .components(material('redstone'), material('silver'), material('energetic_alloy'))
    .color(0x34c3eb).iconSet('SHINY')
    .flags('generate_plate', 'generate_rod', 'generate_frame', 'generate_dense', 'generate_rotor')
.build()

 materialBuilder(32113, 'vivid_alloy')
    .ingot().fluid()
    .blastTemp(5600, "HIGH")
    .components(material('silver'), material('energetic_alloy'))
    .color(0x59f1ff).iconSet('SHINY')
    .flags('generate_plate', 'generate_rod', 'generate_frame', 'generate_dense', 'generate_rotor')
.build()

 materialBuilder(32114, 'pulsating_iron')
    .ingot().fluid()
    .blastTemp(2700, "MID")
    .components(material('iron'), material('energetic_alloy'))
    .color(0x73ffad).iconSet('METALLIC')
    .flags('generate_plate', 'generate_rod', 'generate_frame', 'generate_dense', 'generate_rotor')
.build()

materialBuilder(32116, 'end_steel')
    .ingot().fluid()
    .blastTemp(3600, "HIGH")
    .components(material('iron'), material('energetic_alloy'))
    .color(0xf7ffdb).iconSet('METALLIC')
    .flags('generate_plate', 'generate_rod', 'generate_frame', 'generate_dense', 'generate_rotor')
.build()

materialBuilder(32117, 'schrabidium_vibranium')
    .ingot().fluid()
    .blastTemp(10200, "HIGHEST")
    .components(material('iron'), material('energetic_alloy'))
    .color(0xabc7ff).iconSet('METALLIC')
    .flags('generate_plate', 'generate_rod', 'generate_frame', 'generate_dense', 'generate_rotor')
.build()

materialBuilder(32118, 'vibranium')
    .ingot().fluid()
    .blastTemp(10200, "HIGHEST")
    .color(0xabc7ff).iconSet('METALLIC')
    .flags('generate_plate', 'generate_rod', 'generate_frame', 'generate_dense', 'generate_rotor')
.build()

materialBuilder(32119, 'shaboinkium')
    .ingot().fluid()
    .blastTemp(3600, "MID")
    .color(0x330404).iconSet('METALLIC')
    .flags('generate_plate', 'generate_rod', 'generate_frame', 'generate_dense', 'generate_rotor')
.build()

materialBuilder(32120, 'soularium')
    .ingot().fluid()
    .blastTemp(3600, "MID")
    .color(0x591e00).iconSet('METALLIC')
    .flags('generate_plate', 'generate_rod', 'generate_frame', 'generate_dense', 'generate_rotor')
.build()

materialBuilder(32135, 'vibrant_alloy')
    .ingot().fluid()
    .blastTemp(3600, "MID")
    .components(material('energetic_alloy'), material('ender_pearl'))
    .color(0xa9ff29).iconSet('METALLIC')
    .flags('generate_plate', 'generate_rod', 'generate_frame', 'generate_dense', 'generate_rotor')
.build()


materialBuilder(32122, 'sigmacum')
    .ingot().fluid()
    .element("Σ")
    .color(0x591e00).iconSet('METALLIC')
    .flags('generate_plate', 'generate_rod', 'generate_frame', 'generate_dense', 'generate_rotor')
.build()

materialBuilder(32125, 'desh')
    .ingot().fluid()
    .blastTemp(3600, "MID")
    .components(material('rare_earth'), material('mercury'))
    .color(0xff0000).iconSet('SHINY')
    .flags('generate_plate', 'generate_rod', 'generate_frame', 'generate_dense', 'generate_rotor')
.build()

materialBuilder(32131, 'signalum')
    .ingot().fluid()
    .blastTemp(3600, "MID")
    .color(0xff3700).iconSet('SHINY')
    .components(material('redstone'), material('schrabidium'), material('steel'), material('energetic_alloy'))
    .flags('generate_plate', 'generate_rod', 'generate_frame', 'generate_dense', 'generate_rotor')
.build()


materialBuilder(32126, 'xen')
    .gem()
    .color(0xfffb00).iconSet('SHINY')
.build()

materialBuilder(32127, 'omegnalium')
    .ingot().fluid()
    .blastTemp(10200, "HIGHEST")
    .element("Omegnalium")
    .color(0x120063).iconSet('SHINY')
    .flags('generate_plate', 'generate_rod', 'generate_frame', 'generate_dense', 'generate_rotor')
    .toolStats(toolBuilder(1200, 12000, 1200000, 21)
            .unbreakable() // makes the tools unbreakable (default false)
            .magnetic() // Blocks mined with a tool of this materials go straight into the player inventory (default false)
    )
.build()

materialBuilder(32121, 'adamantium')
    .ingot().fluid()
    .blastTemp(2700, "MID")
    .element("Adamantium")
    .color(0xff0000).iconSet('SHINY')
    .flags('generate_plate', 'generate_rod', 'generate_frame', 'generate_dense', 'generate_rotor')
    .toolStats(toolBuilder(12, 95, 12000, 12))
.build()

materialBuilder(32130, 'manasteel')
    .ingot().fluid()
    .blastTemp(2700, "MID")
    .element("Manasteel")
    .color(0x0095ff).iconSet('SHINY')
    .flags('generate_plate', 'generate_rod', 'generate_frame', 'generate_dense', 'generate_rotor')
    .toolStats(toolBuilder(6, 5, 1245, 4))
.build()

materialBuilder(32132, 'terrasteel')
    .ingot().fluid()
    .blastTemp(2700, "MID")
    .element("Terrasteel")
    .color(0x00ff33).iconSet('SHINY')
    .flags('generate_plate', 'generate_rod', 'generate_frame', 'generate_dense', 'generate_rotor')
    .toolStats(toolBuilder(6, 5, 1245, 4))
.build()

materialBuilder(32133, 'hiihirokane')
    .ingot().fluid()
    .blastTemp(10200, "HIGHEST")
    .element("Hiihirokane")
    .color(0xde0029).iconSet('METALLIC')
    .flags('generate_plate', 'generate_rod', 'generate_frame', 'generate_dense', 'generate_rotor', "no_smelting")
    .toolStats(toolBuilder(25, 150, 92400, 21))
.build()

materialBuilder(32142, 'mythril')
    .ingot().fluid()
    .blastTemp(2700, "MID")
    .components(material("manasteel"), material('terrasteel'))
    .color(0x0095ff).iconSet('SHINY')
    .flags('generate_plate', 'generate_rod', 'generate_frame', 'generate_dense', 'generate_rotor', "no_smelting")
    .toolStats(toolBuilder(12, 95, 12000, 12))
.build()

materialBuilder(32145, 'redstone_alloy')
    .ingot().fluid()
    .blastTemp(2700, "MID")
    .components(material("redstone"), material('stainless_steel'))
    .colorAverage().iconSet('SHINY')
    .flags('generate_plate', 'generate_rod', 'generate_frame', 'generate_dense', 'generate_rotor', "no_smelting")
    .toolStats(toolBuilder(12, 12, 1245, 6))
.build()

materialBuilder(32146, 'conductive_iron')
    .ingot().fluid()
    .blastTemp(2700, "MID")
    .components(material("redstone"), material('iron'))
    .color(0xffbfbf).iconSet('DULL')
    .flags('generate_plate', 'generate_rod', 'generate_frame', 'generate_dense', 'generate_rotor', "no_smelting")
    .toolStats(toolBuilder(3, 6, 600, 6))
.build()

materialBuilder(32147, 'crystalline_alloy')
    .ingot().fluid()
    .blastTemp(5400, "HIGH")
    .components(material("gold"), material('ender_pearl'))
    .color(0xa1ffe9).iconSet('DULL')
    .flags('generate_plate', 'generate_rod', 'generate_frame', 'generate_dense', 'generate_rotor', "no_smelting")
    .toolStats(toolBuilder(3, 4000, 40, 6))
.build()

materialBuilder(32148, 'melodic_alloy')
    .ingot().fluid()
    .blastTemp(2701, "HIGH")
    .components(material("end_steel"), material('ender_pearl'))
    .color(0xdca1ff).iconSet('DULL')
    .flags('generate_plate', 'generate_rod', 'generate_frame', 'generate_dense', 'generate_rotor', "no_smelting")
    .toolStats(toolBuilder(3, 120, 40, 6))
.build()

materialBuilder(32149, 'stellar_alloy')
    .ingot().fluid()
    .blastTemp(3200, "HIGH")
    .components(material("end_steel"), material('ender_pearl'))
    .color(0xeed1ff).iconSet('DULL')
    .flags('generate_plate', 'generate_rod', 'generate_frame', 'generate_dense', 'generate_rotor', "no_smelting")
    .toolStats(toolBuilder(3, 480, 12000, 6))
.build()

materialBuilder(32151, 'antiferrachloric_dineutronium_draconium_schrabidate')
    .ingot().fluid()
    .blastTemp(9001, "HIGHEST")
    .components(material("neutronium"), material('draconium'), material('schrabidium'), material('chlorine'), material('iron'))
    .colorAverage().iconSet('DULL')
    .flags('generate_plate', 'generate_rod', 'generate_frame', 'generate_dense', 'generate_rotor', "no_smelting")
    .cableProperties(8388608, 2, 120, false)
.build()

materialBuilder(32152, 'supercooled_afcdnds')
    .ingot().fluid()
    .components(material("neutronium"), material('draconium'), material('schrabidium'), material('chlorine'), material('iron'))
    .colorAverage().iconSet('SHINY')
    .flags('generate_plate', 'generate_rod', 'generate_frame', 'generate_dense', 'generate_rotor', "no_smelting")
    .cableProperties(8388608, 2, 0, true)
.build()

 materialBuilder(32153, 'exoticium')
        .liquid(fluidBuilder())
        .color(0xd6e9ff)
.build()

materialBuilder(32154, 'stable_neoveline')
    .ingot().fluid()
    .components(material("draconium"), material("xenon"), material('iodine'), material('astatine'), material('caesium'), material('lead'), material('gold'), material('strontium'))
    .color(0xb0f542).iconSet('SHINY')
    .flags('generate_plate', 'generate_rod', 'generate_frame', 'generate_dense', 'generate_rotor', "no_smelting")
    .cableProperties(832408, 16, 2400, false)
.build()

materialBuilder(32155, 'astanene')
    .ingot().fluid()
    .blastTemp(9001, "HIGHEST")
    .components(material("arsenic"), material("carbon"), material('iodine'), material('astatine'), material('caesium'), material('lead'), material('diamond'), material('redstone'))
    .color(0x063600).iconSet('DULL')
    .flags('generate_plate', 'generate_rod', 'generate_frame', 'generate_dense', 'generate_rotor', "no_smelting", "generate_gear")
    .cableProperties(33554432, 12, 2400, false)
.build()

 materialBuilder(32156,'twinitrixite')
    .color(0xb0f542)
    .flags()
    .separatedInto(material('germanium'), material('yttrium'))
    .cableProperties(120, 1, 20, false)
.build()

materialBuilder(32157, 'demetarium')
    .ingot().fluid()
    .components(material("arsenic"), material("helium"), material('hydrogen'), material('redstone'), material('cadmium'), material('lead'), material('silver'), material('argon'))
    .colorAverage().iconSet('DULL')
    .flags('generate_plate', 'generate_rod', 'generate_frame', 'generate_dense', 'generate_rotor', "no_smelting", "generate_gear")
    .cableProperties(33554432, 12, 0, true)
.build()

materialBuilder(32141, 'fluix')
    .gem()
    .components(material("nether_quartz"), material("redstone"), material('indium'), material('lithium'))
    .color(0x5400a3).iconSet('CERTUS')
    .flags()
.build()

materialBuilder(32161, 'gem_grade_fluix_dust')
    .dust()
    .components(material("fluix"), material('indium'), material('lithium'))
    .colorAverage().iconSet('CERTUS')
    .flags()
.build()


 materialBuilder(32158, 'nitanrocketfuel')
        .liquid(fluidBuilder())
        .color(0x9800eb)
.build()

 materialBuilder(32159, 'robustnuclearfuel')
        .liquid(fluidBuilder())
        .color(0xa9ff29)
.build()
}