
recipemap('assembler').recipeBuilder()
        .inputs(ore('wireFineAluminium') * 2)
        .inputs(item('gregtech:meta_item_1', 402))
        .fluidInputs(fluid('tin') * 288 )
        .outputs(item('hbm:circuit_raw'))
        .duration(1700).EUt(24).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(ore('wireFineAnnealedCopper') * 2)
        .inputs(ore('componentDiode'))
        .inputs(ore('componentResistor') * 2)
        .inputs(item('hbm:circuit_aluminium') * 2)
        .fluidInputs(fluid('tin') * 288 )
        .outputs(item('hbm:circuit_targeting_tier1'))
        .duration(1700).EUt(24).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(ore('wireFineAluminium') * 2)
        .inputs(ore('componentDiode') * 8)
        .inputs(ore('componentResistor') * 16)
        .inputs(item('hbm:circuit_copper') * 2)
        .fluidInputs(fluid('tin') * 288 )
        .outputs(item('hbm:circuit_targeting_tier2'))
        .duration(1700).EUt(48).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(ore('wireFineGold') * 2)
        .inputs(ore('componentCapacitor') * 12)
        .inputs(ore('componentResistor') * 16)
        .inputs(item('hbm:circuit_red_copper') * 2)
        .fluidInputs(fluid('tin') * 288 )
        .outputs(item('hbm:circuit_targeting_tier3'))
        .duration(1700).EUt(48).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(ore('wireFineElectrum') * 2)
        .inputs(ore('componentCapacitor') * 24)
        .inputs(ore('componentResistor') * 16)
        .inputs(ore('componentInductor') * 8)
        .inputs(item('hbm:circuit_gold') * 2)
        .fluidInputs(fluid('tin') * 288 )
        .outputs(item('hbm:circuit_targeting_tier4'))
        .duration(1700).EUt(48).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(ore('wireFineSchrabidium') * 2)
        .inputs(ore('componentCapacitor') * 48)
        .inputs(ore('componentResistor') * 32)
        .inputs(ore('componentInductor') * 12)
        .inputs(item('hbm:circuit_schrabidium') * 2)
        .fluidInputs(fluid('schrabidium') * 144 )
        .outputs(item('hbm:circuit_targeting_tier5'))
        .duration(1700).EUt(128).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(ore('wireFineCopper') * 9)
        .inputs(ore('plateSteel') * 12)
        .inputs(item('hbm:circuit_targeting_tier3'))
        .inputs(item('hbm:n2_charge') * 2)
       .inputs(item('hbm:hull_big_steel') * 3)
        .fluidInputs(fluid('aluminium') * 144 )
        .outputs(item('hbm:warhead_n2'))
        .duration(1700).EUt(128).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(item('hbm:warhead_n2'))
        .inputs(ore('plateSteel') * 32)
        .inputs(item('hbm:circuit_targeting_tier4'))
       .inputs(item('hbm:fuel_tank_large') * 3)
       .inputs(item('hbm:thruster_large'))
        .fluidInputs(fluid('aluminium') * 144 )
        .outputs(item('hbm:missile_n2'))
        .duration(800).EUt(128).buildAndRegister()


recipemap('assembler').recipeBuilder()
        .inputs(item('gregtech:meta_item_1', 128))
        .inputs(ore('plateSteel') * 12)
        .inputs(ore('wireFineGold') * 48)
        .inputs(item('hbm:circuit_targeting_tier3'))
       .inputs(item('hbm:fuel_tank_large') * 3)
        .fluidInputs(fluid('aluminium') * 144 )
        .outputs(item('hbm:thruster_large'))
        .duration(240).EUt(128).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(item('gregtech:machine', 1611))
        .inputs(item('hbm:fuel_tank_medium') * 3)
        .inputs(ore('plateSteel') * 12)
        .inputs(ore('wireFineAnnealedCopper') * 48)
        .fluidInputs(fluid('aluminium') * 144 )
        .outputs(item('hbm:fuel_tank_large'))
        .duration(240).EUt(128).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(item('hbm:therm_exo') * 3)
        .inputs(ore('plateSteel') * 12)
        .inputs(ore('wireFineAnnealedCopper') * 16)
        .fluidInputs(fluid('aluminium') * 144 )
        .outputs(item('hbm:warhead_thermo_exo'))
        .duration(240).EUt(128).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(item('hbm:therm_endo') * 3)
        .inputs(ore('plateSteel') * 12)
        .inputs(ore('wireFineAnnealedCopper') * 16)
        .fluidInputs(fluid('aluminium') * 144 )
        .outputs(item('hbm:warhead_thermo_endo'))
        .duration(240).EUt(128).buildAndRegister()
        
recipemap('assembler').recipeBuilder()
        .inputs(ore('plateBlackSteel') * 2)
        .inputs(ore('plateStainlessSteel') * 16)
        .inputs(ore('plateAluminium') * 8)
        .inputs(item('hbm:thruster_large') * 2)
        .inputs(item('hbm:fuel_tank_large'))
        .inputs(item('hbm:warhead_thermo_exo'))
        .inputs(item('hbm:circuit_targeting_tier3') * 2)
        .fluidInputs(fluid('stainless_steel') * 120)
        .outputs(item('hbm:missile_exo'))
        .duration(1200).EUt(240).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(ore('plateBlackSteel') * 2)
        .inputs(ore('plateStainlessSteel') * 16)
        .inputs(ore('plateAluminium') * 8)
        .inputs(item('hbm:thruster_large') * 2)
        .inputs(item('hbm:fuel_tank_large'))
        .inputs(item('hbm:warhead_thermo_endo'))
        .inputs(item('hbm:circuit_targeting_tier3') * 2)
        .fluidInputs(fluid('stainless_steel') * 120)
        .outputs(item('hbm:missile_endo'))
        .duration(1200).EUt(240).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(ore('plateSteel') * 9)
        .inputs(ore('anyPlasticexplosive') * 12)
        .inputs(ore('nuggetUranium') * 3)
        .inputs(ore('ingotLithium') * 3)
        .inputs(item('hbm:cell').withNbt(['HbmFluidKey': ['FluidName': 'deuterium', 'Amount': 1000]]) * 8)
        .fluidInputs(fluid('lead') * 1440 )
        .outputs(item('hbm:warhead_mirv'))
        .duration(240).EUt(128).buildAndRegister()
        
recipemap('assembler').recipeBuilder()
        .inputs(ore('plateBlackSteel') * 2)
        .inputs(ore('plateStainlessSteel') * 16)
        .inputs(ore('plateAluminium') * 8)
        .inputs(item('hbm:thruster_large') * 2)
        .inputs(item('hbm:fuel_tank_large'))
        .inputs(item('hbm:warhead_mirv'))
        .inputs(item('hbm:circuit_targeting_tier5') * 2)
        .fluidInputs(fluid('stainless_steel') * 120)
        .outputs(item('hbm:missile_nuclear_cluster'))
        .duration(1200).EUt(240).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(ore('plateSteel') * 9)
        .inputs(ore('wireFineCopper') * 6)
        .inputs(ore('nuggetUranium') * 3)
        .inputs(item('hbm:boy_shielding'))
       .inputs(item('hbm:boy_target'))
       .inputs(item('hbm:boy_bullet'))
       .inputs(item('hbm:boy_propellant'))
        .fluidInputs(fluid('lead') * 1440 )
        .outputs(item('hbm:warhead_nuclear'))
        .duration(240).EUt(128).buildAndRegister()
        
recipemap('assembler').recipeBuilder()
        .inputs(ore('plateSteel') * 9)
        .inputs(ore('wireFineCopper') * 6)
        .inputs(ore('nuggetUranium') * 3)
        .inputs(item('hbm:boy_shielding'))
       .inputs(item('hbm:boy_target'))
       .inputs(item('hbm:boy_bullet'))
       .inputs(item('hbm:boy_propellant'))
        .fluidInputs(fluid('lead') * 1440 )
        .outputs(item('hbm:warhead_nuclear'))
        .duration(240).EUt(128).buildAndRegister()
        
        
recipemap('assembler').recipeBuilder()
        .inputs(ore('plateUranium') * 3)
        .fluidInputs(fluid('lead') * 144 )
        .outputs(item('hbm:boy_target'))
        .duration(80).EUt(20).buildAndRegister()
                
recipemap('assembler').recipeBuilder()
        .inputs(ore('plateUranium') * 2)
        .fluidInputs(fluid('lead') * 144 )
        .outputs(item('hbm:boy_bullet'))
        .duration(80).EUt(10).buildAndRegister()
                
recipemap('assembler').recipeBuilder()
        .inputs(ore('plateTungCar') * 12)
        .fluidInputs(fluid('steel') * 288 )
        .outputs(item('hbm:boy_shielding'))
        .duration(80).EUt(10).buildAndRegister()
                
recipemap('assembler').recipeBuilder()
        .inputs(ore('plateSteel') * 4)
        .fluidInputs(fluid('nitroglycerin') * 288 )
        .outputs(item('hbm:boy_propellant'))
        .duration(80).EUt(10).buildAndRegister()