
recipemap('electric_blast_furnace').recipeBuilder()
        .inputs(ore('plateLead') * 2)
        .inputs(ore('dustDiamond'))
        .fluidInputs(fluid('steel') * 250 )
        .outputs(item('hbm:neutron_reflector'))
        .property("temperature", 2001)
        .duration(5600).EUt(512).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .fluidInputs(fluid('smear') * 1000 )
        .fluidOutputs(fluid('reclaimed') * 500)
        .duration(5600).EUt(512).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .fluidInputs(fluid('reclaimed') * 1000 )
        .fluidInputs(fluid('lubricant') * 500 )
        .fluidOutputs(fluid('petroil') * 500)
        .duration(1200).EUt(512).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .fluidInputs(fluid('oil') * 300 )
        .outputs(item('hbm:solid_fuel'))
        .duration(120).EUt(6).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .fluidInputs(fluid('reclaimed') * 300 )
        .outputs(item('hbm:solid_fuel'))
        .duration(120).EUt(6).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .fluidInputs(fluid('petroil') * 300 )
        .outputs(item('hbm:solid_fuel'))
        .duration(120).EUt(6).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .fluidInputs(fluid('naphtha') * 300 )
        .outputs(item('hbm:solid_fuel'))
        .duration(120).EUt(6).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .fluidInputs(fluid('diesel') * 300 )
        .outputs(item('hbm:solid_fuel'))
        .duration(120).EUt(6).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .fluidInputs(fluid('light_fuel') * 300 )
        .outputs(item('hbm:solid_fuel'))
        .duration(120).EUt(6).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .inputs(ore('oreOilsands'))
        .inputs(ore('sand') * 16)
        .fluidOutputs(fluid('bitumen') * 144)
        .duration(120).EUt(6).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .inputs(ore('gravel' * 8))
        .fluidInputs(fluid('bitumen') * 8000 )
        .inputs(ore('sand') * 16)
        .outputs(item('hbm:asphalt') * 16)
        .duration(180).EUt(6).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .inputs(item('hbm:powder_ice') * 8)
        .fluidInputs(fluid('coolant') * 1200 )
        .fluidOutputs(fluid('cryogel') * 16)
        .duration(120).EUt(6).buildAndRegister()

recipemap('large_chemical_reactor').recipeBuilder()
        .inputs(item('hbm:circuit_gold'))
        .inputs(ore('plateDesh'))
        .inputs(ore('dustSchrabidium'))
        .fluidInputs(fluid('acid') * 1200 )
        .outputs(item('hbm:circuit_schrabidium'))
        .duration(120).EUt(510).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .fluidInputs(fluid('nitric_acid') * 100 )
        .fluidInputs(fluid('glycerol') * 1200 )
        .fluidOutputs(fluid('nitroglycerin') * 320)
        .duration(620).EUt(120).buildAndRegister()
        
recipemap('large_chemical_reactor').recipeBuilder()
        .inputs(ore('sand'))
        .inputs(ore('dustSaltpeter'))
        .inputs(ore('dustSugar'))
        .outputs(item('hbm:ball_dynamite') * 2)
        .duration(620).EUt(120).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .inputs(ore('dustSaltpeter'))
        .inputs(ore('platePlastic') * 3 )
        .outputs(item('hbm:ingot_c4'))
        .duration(620).EUt(120).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .inputs(ore('dustSaltpeter'))
        .inputs(ore('plankWood') * 3 )
        .outputs(item('hbm:cordite'))
        .duration(620).EUt(120).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .inputs(ore('sand'))
        .inputs(ore('gravel') * 3 )
        .fluidInputs(fluid('water') * 100 )
        .outputs(item('hbm:concrete_smooth'))
        .duration(620).EUt(120).buildAndRegister()

recipemap('large_chemical_reactor').recipeBuilder()
        .inputs(ore('sand'))
        .inputs(ore('dustAsbestos'))
        .inputs(ore('gravel') * 3 )
        .fluidInputs(fluid('water') * 100 )
        .outputs(item('hbm:concrete_asbestos') * 16)
        .duration(620).EUt(120).buildAndRegister()

recipemap('large_chemical_reactor').recipeBuilder()
        .inputs(ore('sand'))
        .inputs(ore('gravel') * 3 )
        .inputs(ore('billetU38'))
        .fluidInputs(fluid('concrete') * 144 )
        .outputs(item('hbm:ducrete') * 16)
        .duration(620).EUt(120).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .inputs(ore('dustIron'))
        .fluidInputs(fluid('schrabidic') * 100 )
        .outputs(item('hbm:powder_schrabidate'))
        .duration(620).EUt(120).buildAndRegister()

recipemap('distillery').recipeBuilder()
        .fluidInputs(fluid('oil_heavy') * 100 )
        .fluidOutputs(fluid('bitumen') * 30)
        .duration(620).EUt(72).buildAndRegister()

recipemap('distillery').recipeBuilder()
        .fluidInputs(fluid('oil_heavy') * 100 )
        .fluidOutputs(fluid('smear') * 70)
        .circuitMeta(20)
        .duration(620).EUt(72).buildAndRegister()

recipemap('distillery').recipeBuilder()
        .fluidInputs(fluid('oil_heavy') * 100 )
        .circuitMeta(19)
        .fluidOutputs(fluid('heatingoil') * 60)
        .duration(620).EUt(72).buildAndRegister()

recipemap('distillery').recipeBuilder()
        .fluidInputs(fluid('smear') * 100 )
        .fluidOutputs(fluid('lubricant') * 40)
        .duration(620).EUt(72).buildAndRegister()