recipemap('chemical_reactor').recipeBuilder()
        .fluidInputs(fluid('antineutronium') * 100)
        .fluidInputs(fluid('supercoolant') * 25000)
        .fluidOutputs(fluid('low_enriched_draconic_solution') * 100)
        .duration(1200).EUt(200000).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .fluidInputs(fluid('low_enriched_draconic_solution') * 100)
        .inputs(ore('dustNeptunium') * 6)
        .inputs(ore('dustTungsten') * 24)
        .fluidOutputs(fluid('enriched_draconic_solution') * 12)
        .duration(2400).EUt(200000).buildAndRegister()

recipemap('plasma_generator').recipeBuilder()
        .fluidInputs(fluid('enriched_draconic_solution') * 100)
        .fluidOutputs(fluid('draconium') * 12)
        .duration(2400).EUt(400000).buildAndRegister()

recipemap('electric_blast_furnace').recipeBuilder()
        .inputs(ore('dustDraconium'))
        .fluidInputs(fluid('oxygen') * 250 )
        .outputs(item('gregtech:meta_ingot', 32111))
        .property("temperature", 9200)
        .duration(1200).EUt(200000).buildAndRegister()