// Remove Wrong Aluminium
<ore:blockAluminum>.remove(<ore:blockAluminum>.firstItem);
<ore:blockAluminum>.remove(<libvulpes:metal0:9>);
<ore:ingotAluminum>.remove(<ore:ingotAluminum>.firstItem);

// Certus Compatability
<ore:crystalCertusQuartz>.add(<metaitem:gemCertusQuartz>);
<ore:gemCertusQuartz>.remove(<ore:gemCertusQuartz>.firstItem);

import mods.thaumcraft.ArcaneWorkbench;
val gemLatex = <ore:gemLatex>;
gemLatex.remove(<hbm:ball_resin>);
val ingotAnyRubber = <ore:ingotAnyRubber>;
ingotAnyRubber.remove(<gregtech:meta_ingot:1068>);
ingotAnyRubber.remove(<hbm:ingot_biorubber>);
ingotAnyRubber.add(<gregtech:meta_ingot:1004>);
val ingotOsmiridium = <ore:ingotOsmiridium>;
ingotOsmiridium.remove(<gregtech:meta_ingot:344>);
val nuggetOsmiridium = <ore:nuggetOsmiridium>;
nuggetOsmiridium.remove(<gregtech:meta_nugget:344>);
val dustOsmiridium = <ore:dustOsmiridium>;
dustOsmiridium.remove(<gregtech:meta_dust:344>);
val ingotBronze = <ore:ingotBronze>;
ingotBronze.remove(<lucraftcore:ingot_bronze>);
ingotBronze.remove(<thermalfoundation:material:163>);
val ingotTin = <ore:ingotTin>;
ingotTin.remove(<lucraftcore:ingot_tin>);
ingotTin.remove(<thermalfoundation:material:129>);
val ingotCopper = <ore:ingotCopper>;
ingotCopper.remove(<lucraftcore:ingot_copper>);
ingotCopper.remove(<thermalfoundation:material:128>);
ingotCopper.remove(<hbm:ingot_copper>);
val ingotSilver = <ore:ingotSilver>;
ingotSilver.remove(<lucraftcore:ingot_silver>);
ingotSilver.remove(<thermalfoundation:material:130>);
val ingotNickel = <ore:ingotNickel>;
ingotNickel.remove(<lucraftcore:ingot_nickel>);
ingotNickel.remove(<thermalfoundation:material:133>);
val ingotLead = <ore:ingotLead>;
ingotLead.remove(<lucraftcore:ingot_lead>);
ingotLead.remove(<thermalfoundation:material:131>);
ingotLead.remove(<hbm:ingot_lead>);
val ingotTitanium = <ore:ingotTitanium>;
ingotTitanium.remove(<lucraftcore:ingot_titanium>);
ingotTitanium.remove(<hbm:ingot_titanium>);
val ingotOsmium = <ore:ingotOsmium>;
ingotOsmium.remove(<lucraftcore:ingot_osmium>);
val ingotIridium = <ore:ingotIridium>;
ingotIridium.remove(<lucraftcore:ingot_iridium>);
ingotIridium.remove(<thermalfoundation:material:135>);
val ingotUranium = <ore:ingotUranium>;
ingotUranium.remove(<lucraftcore:ingot_uranium>);
ingotUranium.remove(<hbm:ingot_uranium>);
val ingotSteel = <ore:ingotSteel>;
ingotSteel.remove(<lucraftcore:ingot_steel>);
ingotSteel.remove(<hbm:ingot_steel>);
ingotSteel.remove(<thermalfoundation:material:160>);
ingotSteel.remove(<industrialrenewal:ingot_steel>);
val ingotTungsten = <ore:ingotTungsten>;
ingotTungsten.remove(<hbm:ingot_tungsten>);
val ingotAluminium = <ore:ingotAluminium>;
ingotAluminium.remove(<hbm:ingot_aluminium>);
val ingotAluminum = <ore:ingotAluminum>;
ingotAluminum.remove(<thermalfoundation:material:132>);
val ingotPlatinum = <ore:ingotPlatinum>;
ingotPlatinum.remove(<thermalfoundation:material:134>);
val ingotElectrum = <ore:ingotElectrum>;
ingotElectrum.remove(<thermalfoundation:material:161>);
val ingotConstantan = <ore:ingotConstantan>;
val ingotInvar = <ore:ingotInvar>;
ingotInvar.remove(<thermalfoundation:material:162>);
val ingotTantalum = <ore:ingotTantalum>;
ingotTantalum.remove(<hbm:ingot_tantalium>);
val ingotPlutonium = <ore:ingotPlutonium>;
ingotPlutonium.remove(<hbm:ingot_plutonium>);
val ingotPlutonium241 = <ore:ingotPlutonium241>;
ingotPlutonium241.remove(<gregtech:meta_ingot:82>);
val ingotPalladium = <ore:iningotPalladium>;
ingotPalladium.remove(<lucraftcore:ingot_palladium>);
val ingotCobalt = <ore:ingotCobalt>;
ingotCobalt.remove(<gregtech:meta_ingot:23>);
val ingotUranium238 = <ore:ingotUranium238>;
ingotUranium238.remove(<hbm:ingot_u238>);
val ingotUranium235 = <ore:ingotUranium235>;
ingotUranium235.remove(<hbm:ingot_u235>);
val ingotBrass = <ore:ingotBrass>;
ingotBrass.remove(<gregtech:meta_ingot:259>);
val stickSteel = <ore:stickSteel>;
stickSteel.remove(<industrialrenewal:stick_steel>);
val stickIron = <ore:stickIron>;
stickIron.remove(<industrialrenewal:stick_iron>);
val oreIron = <ore:oreIron>;
oreIron.remove(<industrialrenewal:orevein_hematite>);
oreIron.remove(<industrialrenewal:chunk_hematite>);
val blockSteel = <ore:blockSteel>;
blockSteel.remove(<lucraftcore:block_steel>);
blockSteel.remove(<thermalfoundation:storage_alloy:0>);
blockSteel.remove(<industrialrenewal:block_steel>);
