
recipemap('chemical_reactor').recipeBuilder()
        .inputs(ore('dustFluix') * 2)
        .inputs(ore('dustSilver') * 1)
        .fluidInputs(fluid('pure_fluix_slurry') * 144 )
        .fluidInputs(fluid('quartz_soldering_mixture') * 72)
        .fluidOutputs(fluid('fluix_soldering_alloy') * 144)
        .duration(620).EUt(220).buildAndRegister()
    
recipemap('assembler').recipeBuilder()
        .inputs(item('appliedenergistics2:material', 38) * 3)
        .inputs(ore('dustFluix') * 24)
        .inputs(ore('circuitHv') * 2)
        .inputs(ore('screwStainlessSteel') * 2)
       .inputs(ore('gemFlawlessCertusQuartz'))
        .fluidInputs(fluid('fluix_soldering_alloy') * 70)
        .outputs(item('nae2:material', 1))
        .duration(620).EUt(220).buildAndRegister()

recipemap('assembler').recipeBuilder()
    .inputs(item('nae2:material', 1) * 3)
    .inputs(ore('dustFluix') * 32)
    .inputs(ore('circuitEv') * 3)
    .inputs(ore('gemFlawlessCertusQuartz') * 2)
    .inputs(ore('screwAluminium') * 2)
    .inputs(item('threng:material', 4) * 2)
    .inputs(item('appliedenergistics2:material', 23) * 2)
    .fluidInputs(fluid('fluix_soldering_alloy') * 100)
    .outputs(item('nae2:material', 2))
    .duration(740).EUt(240).buildAndRegister()

recipemap('assembler').recipeBuilder()
    .inputs(item('nae2:material', 2) * 3)
    .inputs(ore('dustFluix') * 40)
    .inputs(ore('circuitIv') * 4)
    .inputs(ore('gemFlawlessCertusQuartz') * 3)
    .inputs(ore('screwStainlessSteel') * 2)
    .inputs(item('threng:material', 4) * 2)
    .inputs(item('appliedenergistics2:material', 23) * 2)
    .fluidInputs(fluid('fluix_soldering_alloy') * 130)
    .outputs(item('nae2:material', 3))
    .duration(880).EUt(260).buildAndRegister()

recipemap('assembler').recipeBuilder()
    .inputs(item('nae2:material', 3) * 3)
    .inputs(ore('dustFluix') * 48)
    .inputs(ore('circuitLuv') * 5)
    .inputs(ore('gemExquisiteCertusQuartz') * 4)
    .inputs(ore('screwTitanium') * 2)
    .inputs(item('threng:material', 4) * 2)
    .inputs(item('appliedenergistics2:material', 23) * 2)
    .fluidInputs(fluid('fluix_soldering_alloy') * 160)
    .outputs(item('nae2:material', 4))
    .duration(1040).EUt(2080).buildAndRegister()


recipemap('assembler').recipeBuilder()
    .inputs(item('nae2:material', 5) * 3)
    .inputs(item('gregtech:transparent_casing', 2) * 4)
    .inputs(ore('dustFluix') * 24)
    .inputs(ore('circuitHv') * 2)
    .inputs(ore('screwStainlessSteel') * 2)
    .inputs(ore('gemFlawlessCertusQuartz') * 1)
    .inputs(item('threng:material', 4) * 2)
    .inputs(item('appliedenergistics2:material', 23) * 2)
    .fluidInputs(fluid('fluix_soldering_alloy') * 70)
    .outputs(item('nae2:material', 6))
    .duration(620).EUt(220).buildAndRegister()

recipemap('assembler').recipeBuilder()
    .inputs(item('nae2:material', 6) * 3)
    .inputs(item('gregtech:transparent_casing', 2) * 6)
    .inputs(ore('dustFluix') * 32)
    .inputs(ore('circuitEv') * 3)
    .inputs(ore('screwAluminium') * 3)
    .inputs(ore('gemFlawlessCertusQuartz') * 2)
    .inputs(item('threng:material', 4) * 2)
    .inputs(item('appliedenergistics2:material', 23) * 2)
    .fluidInputs(fluid('fluix_soldering_alloy') * 100)
    .outputs(item('nae2:material', 7))
    .duration(740).EUt(240).buildAndRegister()

recipemap('assembler').recipeBuilder()
    .inputs(item('nae2:material', 7) * 3)
    .inputs(item('gregtech:transparent_casing', 2) * 8)
    .inputs(ore('dustFluix') * 40)
    .inputs(ore('circuitIv') * 4)
    .inputs(ore('screwStainlessSteel') * 4)
    .inputs(ore('gemFlawlessCertusQuartz') * 3)
    .inputs(item('threng:material', 4) * 2)
    .inputs(item('appliedenergistics2:material', 23) * 2)
    .fluidInputs(fluid('fluix_soldering_alloy') * 130)
    .outputs(item('nae2:material', 8))
    .duration(880).EUt(260).buildAndRegister()

recipemap('assembler').recipeBuilder()
    .inputs(ore('dustFluix') * 12)
    .inputs(ore('circuitUlv') * 2)
    .inputs(ore('screwStainlessSteel') * 4)
    .inputs(ore('platePlastic'))
    .inputs(ore('crystalCertusQuartz'))
    .inputs(item('appliedenergistics2:material', 22) * 2)
    .inputs(item('appliedenergistics2:material', 23) * 2)
    .fluidInputs(fluid('fluix_soldering_alloy') * 12)
    .outputs(item('appliedenergistics2:material', 35))
    .duration(140).EUt(12).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .inputs(ore('enderpearl'))
    .fluidInputs(fluid('pure_fluix_slurry') * 288)
    .outputs(item('appliedenergistics2:material', 9))
    .duration(20).EUt(12).buildAndRegister()


recipemap('chemical_reactor').recipeBuilder()
        .inputs(ore('blockGlass') * 5)
    .fluidInputs(fluid('quartz_soldering_mixture') * 144)
    .outputs(item('appliedenergistics2:quartz_glass') * 5)
    .duration(20).EUt(12).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .inputs(ore('blockGlass') * 5)
    .fluidInputs(fluid('quartz_soldering_mixture_2') * 72)
    .outputs(item('appliedenergistics2:quartz_glass') * 10)
    .duration(20).EUt(6).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .inputs(ore('blockGlass') * 5)
    .fluidInputs(fluid('quartz_soldering_mixture_3') * 36)
    .outputs(item('appliedenergistics2:quartz_glass') * 20)
    .duration(10).EUt(6).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .inputs(ore('blockGlass') * 5)
    .fluidInputs(fluid('quartz_soldering_mixture_4') * 18)
    .outputs(item('appliedenergistics2:quartz_glass') * 60)
    .duration(5).EUt(3).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .inputs(ore('dustNetherQuartz'))
    .fluidInputs(fluid('soldering_alloy') * 144)
    .fluidOutputs(fluid('quartz_soldering_mixture') * 288)
    .duration(20).EUt(12).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .inputs(ore('dustNetherQuartz'))
            .inputs(ore('dustFluix'))
    .fluidInputs(fluid('distilled_water') * 144)
    .fluidOutputs(fluid('quartz_soldering_mixture_2') * 288)
    .duration(20).EUt(12).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .inputs(ore('dustNetherQuartz'))
    .fluidInputs(fluid('radon') * 144)
    .fluidOutputs(fluid('quartz_soldering_mixture_3') * 288)
    .duration(20).EUt(12).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .inputs(ore('dustNetherQuartz'))
    .fluidInputs(fluid('radon') * 144)
    .fluidOutputs(fluid('quartz_soldering_mixture_3') * 288)
    .duration(20).EUt(12).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .inputs(ore('dustCertusQuartz'))
    .fluidInputs(fluid('schrabidium') * 144)
    .fluidOutputs(fluid('quartz_soldering_mixture_4') * 288)
    .duration(20).EUt(12).buildAndRegister()


recipemap('chemical_reactor').recipeBuilder()
        .inputs(ore('dustFluix') * 2)
        .inputs(ore('dustSilver') * 1)
        .fluidInputs(fluid('pure_fluix_slurry') * 72 )
        .fluidInputs(fluid('quartz_soldering_mixture_2') * 36)
        .fluidOutputs(fluid('fluix_soldering_alloy') * 488)
        .duration(320).EUt(110).buildAndRegister()
    
    
recipemap('chemical_reactor').recipeBuilder()
        .inputs(ore('dustFluix') * 2)
        .inputs(ore('dustSilver') * 1)
        .fluidInputs(fluid('pure_fluix_slurry') * 36 )
        .fluidInputs(fluid('quartz_soldering_mixture_2') * 18)
        .fluidOutputs(fluid('fluix_soldering_alloy') * 1008)
        .duration(160).EUt(65).buildAndRegister()
    
    
recipemap('chemical_reactor').recipeBuilder()
        .inputs(ore('dustFluix') * 2)
        .inputs(ore('dustSilver') * 1)
        .fluidInputs(fluid('pure_fluix_slurry') * 18 )
        .fluidInputs(fluid('quartz_soldering_mixture_3') * 9)
        .fluidOutputs(fluid('fluix_soldering_alloy') * 1008)
        .duration(80).EUt(32).buildAndRegister()