mods.pyrotech.chopping_block.recipeBuilder()
    .input(item('minecraft:planks'))
    .output(item('minecraft:wooden_slab') * 2)
    .chops(4, 1)
    .chops(2, 1)
    .chops(1, 1)
    .chops(1, 2)
    .name('vanillarep1')
    .register()

mods.pyrotech.chopping_block.recipeBuilder()
    .input(item('minecraft:planks', 1))
    .output(item('minecraft:wooden_slab', 1) * 2)
    .chops(4, 1)
    .chops(2, 1)
    .chops(1, 1)
    .chops(1, 2)
    .name('vanillarep2')
    .register()

mods.pyrotech.chopping_block.recipeBuilder()
    .input(item('minecraft:planks', 2))
    .output(item('minecraft:wooden_slab', 2) * 2)
    .chops(4, 1)
    .chops(2, 1)
    .chops(1, 1)
    .chops(1, 2)
    .name('vanillarep3')
    .register()


mods.pyrotech.chopping_block.recipeBuilder()
    .input(item('minecraft:planks', 3))
    .output(item('minecraft:wooden_slab', 3) * 2)
    .chops(4, 1)
    .chops(2, 1)
    .chops(1, 1)
    .chops(1, 2)
    .name('vanillarep4')
    .register()

mods.pyrotech.chopping_block.recipeBuilder()
    .input(item('minecraft:planks', 4))
    .output(item('minecraft:wooden_slab', 4) * 2)
    .chops(4, 1)
    .chops(2, 1)
    .chops(1, 1)
    .chops(1, 2)
    .name('vanillarep6')
    .register()

mods.pyrotech.chopping_block.recipeBuilder()
    .input(item('minecraft:planks', 5))
    .output(item('minecraft:wooden_slab', 5) * 2)
    .chops(4, 1)
    .chops(2, 1)
    .chops(1, 1)
    .chops(1, 2)
    .name('vanillarep5')
    .register()

    
mods.pyrotech.chopping_block.recipeBuilder()
    .input(item('pyrotech:material', 20))
    .output(item('gregtech:meta_item_1', 347) * 8)
    .chops(4, 1)
    .chops(2, 1)
    .chops(1, 1)
    .chops(1, 2)
    .name('gaming')
    .register()

    
mods.pyrotech.chopping_block.recipeBuilder()
    .input(item('pyrotech:material', 16))
    .output(metaitem('ingotCarvedMasonry'))
    .chops(4, 1)
    .chops(2, 1)
    .chops(1, 1)
    .chops(1, 2)
    .name('carved_masonry')
    .register()