

// LV
recipemap('chemical_reactor').recipeBuilder()
        .inputs(ore('dustXenon135') * 2 )
        .fluidInputs(fluid('oxygen') * 250 )
        .outputs(item('enderutilities:enderpart') * 2 )
        .duration(400).EUt(60).buildAndRegister()
// MV
recipemap('assembler').recipeBuilder()
         .inputs(ore('dustTin'))
         .inputs(item('gregtech:meta_dust', 320))
         .outputs(item('enderio:item_material', 22))
         .duration(200).EUt(120).buildAndRegister()

recipemap('centrifuge').recipeBuilder()
        .inputs(item('bloodmagic:component:8'))
        .chancedOutput(item('embers:shard_ember'), 500, 500)
        .duration(200).EUt(120).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
         .inputs(ore('dustSulfur') * 2 )
         .fluidInputs(fluid('schrabidium') * 200 )
         .fluidOutputs(fluid('sas3'))
         .duration(600).EUt(120).buildAndRegister()
                
recipemap('chemical_reactor').recipeBuilder()
         .inputs(ore('dustKanthal') * 2 )
         .fluidInputs(fluid('mud_fluid') * 200 )
         .inputs(ore('ingotSteel') * 2 )
         .outputs(item('thermalfoundation:material', 214) * 16)
         .duration(600).EUt(120).buildAndRegister()

recipemap('assembler').recipeBuilder()
         .inputs(ore('stickStainlessSteel') * 2)
         .inputs(ore('plateAdvancedAlloy') * 4)
         .inputs(item('gregtech:machine_casing', 3))
         .outputs(item('thermalexpansion:frame'))
         .duration(200).EUt(120).buildAndRegister()

recipemap('assembler').recipeBuilder()
         .inputs(ore('stickStainlessSteel') * 2)
         .inputs(ore('plateBlueAlloy') * 4)
         .inputs(item('gregtech:machine_casing', 3))
         .outputs(item('thermalexpansion:frame', 64))
         .duration(200).EUt(120).buildAndRegister()

recipemap('electric_blast_furnace').recipeBuilder()
        .inputs(ore('dustRedstone') * 6)
        .inputs(ore('ingotStainlessSteel') * 6)
        .fluidInputs(fluid('oxygen') * 250 )
        .outputs(item('enderio:item_alloy_ingot', 3) * 2)
        .property("temperature", 1200)
        .duration(400).EUt(140).buildAndRegister()

recipemap('electric_blast_furnace').recipeBuilder()
        .inputs(ore('dustRedstone') * 6)
        .inputs(ore('ingotStainlessSteel') * 6)
        .inputs(item('actuallyadditions:item_crystal') * 2)
        .fluidInputs(fluid('oxygen') * 250 )
        .outputs(item('enderio:item_alloy_ingot', 3) * 12)
        .property("temperature", 1200)
        .duration(400).EUt(140).buildAndRegister()

recipemap('electric_blast_furnace').recipeBuilder()
        .inputs(ore('dustRedstone') * 6)
        .inputs(ore('ingotStainlessSteel') * 6)
        .inputs(item('actuallyadditions:item_crystal_empowered') * 2)
        .fluidInputs(fluid('oxygen') * 250 )
        .outputs(item('enderio:item_alloy_ingot', 3) * 32)
        .property("temperature", 1200)
        .duration(400).EUt(140).buildAndRegister()

// Redstone * 1
mods.gregtech.electrolyzer.removeByInput(60, [metaitem('dustEnergeticAlloy') * 4], null)

// HV
recipemap('chemical_reactor').recipeBuilder()
        .inputs(ore('dustDiamond'), ore('dustLithium') * 2)
        .fluidInputs(fluid('ammonia') * 100)
        .outputs(item('libvulpes:productgem'))
        .duration(200).EUt(200).buildAndRegister()

recipemap('mixer').recipeBuilder()
        .inputs(ore('dustIron') * 6)
        .inputs(ore('dustGraphite') * 6)
        .outputs(item('gregtech:meta_dust', 32109) * 12)
        .duration(120).EUt(200).buildAndRegister()
        
recipemap('mixer').recipeBuilder()
        .inputs(ore('dustSilver') * 6)
        .inputs(ore('dustEnergeticAlloy') * 6)
        .outputs(item('gregtech:meta_dust', 32113) * 12)
        .duration(120).EUt(200).buildAndRegister()
                
recipemap('mixer').recipeBuilder()
        .inputs(item('hbm:powder_power') * 2)
        .inputs(ore('dustRedstone') * 6)
        .outputs(item('gregtech:meta_dust', 32110))
        .duration(120).EUt(200).buildAndRegister()

recipemap('mixer').recipeBuilder()
        .inputs(ore('dustSilver') * 6)
        .inputs(ore('dustRedstone') * 6)
        .inputs(ore('dustEnergeticAlloy') * 6)
        .outputs(item('gregtech:meta_dust', 32112) * 12)
        .duration(120).EUt(200).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .fluidInputs(fluid('liquid_air') * 100)
        .fluidInputs(fluid('ammonia') * 250)
        .fluidOutputs(fluid('rocketfuel') * 100)
        .duration(400).EUt(200).buildAndRegister()

recipemap('mixer').recipeBuilder()
        .inputs(ore('dustIron'))
        .inputs(ore('dustCarbon'))
        .outputs(metaitem('dustDarkSteel'))
        .duration(60).EUt(200).buildAndRegister()

recipemap('mixer').recipeBuilder()
        .inputs(ore('dustEndSteel'))
        .inputs(ore('dustEnderPearl'))
        .outputs(metaitem('dustMelodicAlloy'))
        .duration(60).EUt(200).buildAndRegister()

recipemap('mixer').recipeBuilder()
        .inputs(ore('dustDarkSteel'))
        .inputs(ore('dustEnderPearl'))
        .outputs(metaitem('dustEndstone'))
        .duration(60).EUt(200).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(item('appliedenergistics2:quartz_glass') * 2 )
        .inputs(ore('gemFluix') * 4 )
        .fluidInputs(fluid('radon') * 100)
        .outputs(item('appliedenergistics2:part', 16) * 32 )
        .duration(200).EUt(200).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(item('appliedenergistics2:quartz_glass') * 2 )
        .inputs(ore('gemFluix') * 4 )
        .fluidInputs(fluid('quartz_soldering_mixture') * 288)
        .outputs(item('appliedenergistics2:part', 16) * 4 )
        .duration(200).EUt(200).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .inputs(ore('dustAstralStarmetal') * 6)
        .fluidInputs(fluid('plastic') * 500 )
        .fluidInputs(fluid('astralsorcery.liquidstarlight') * 120 )
        .fluidOutputs(fluid('polyastraethylene') * 240 )
        .duration(400).EUt(240).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .inputs(ore('ingotSchrabidium') * 6)
        .inputs(ore('ingotTennessine') * 2)
        .fluidInputs(fluid('radon') * 500 )
        .outputs(item('hbm:pellet_schrabidium'))
        .duration(400).EUt(240).buildAndRegister()

recipemap('assembler').recipeBuilder()
         .inputs(ore('platePlastic') * 4 )
         .fluidInputs(fluid('soldering_alloy') * 72 )
         .inputs(ore('plateVanadiumSteel') * 8 )
         .inputs(ore('rodStainlessSteel') * 2 )
         .inputs(ore('nuggetRedstoneAlloy') * 2 )
         .inputs(item('enderio:item_material', 20))
         .outputs(item('enderio:item_material'))
         .duration(200).EUt(240).buildAndRegister()

recipemap('assembler').recipeBuilder()
         .inputs(ore('platePlastic') * 4 )
         .fluidInputs(fluid('soldering_alloy') * 72 )
         .inputs(ore('plateVanadiumSteel') * 6 )
         .inputs(ore('rodStainlessSteel') * 2 )
         .inputs(ore('nuggetRedstoneAlloy') * 2 )
         .inputs(item('enderio:item_material', 20))
         .outputs(item('enderio:item_material'))
         .duration(200).EUt(240).buildAndRegister()

recipemap('assembler').recipeBuilder()
         .inputs(ore('platePlastic') * 6 )
         .fluidInputs(fluid('soldering_alloy') * 72 )
         .inputs(ore('wireFineSteel') * 4 )
         .inputs(ore('nuggetRedstoneAlloy') * 2 )
         .inputs(ore('circuitMv') * 1 )
         .inputs(item('enderio:item_material', 20))
         .outputs(item('enderio:item_basic_capacitor'))
         .duration(200).EUt(240).buildAndRegister()

recipemap('assembler').recipeBuilder()
         .inputs(ore('wireFineSteel') * 4 )
         .fluidInputs(fluid('soldering_alloy') * 72 )
         .inputs(ore('plateVanadiumSteel') * 4 )
         .inputs(ore('stickRedSteel') * 2 )
         .outputs(item('thermalfoundation:material', 512))
         .duration(200).EUt(240).buildAndRegister()

recipemap('assembler').recipeBuilder()
         .inputs(ore('wireFineGold') * 4 )
         .inputs(ore('dustRedstoneAlloy') * 12 )
         .fluidInputs(fluid('soldering_alloy') * 72 )
         .inputs(ore('foilSilver') * 12 )
         .inputs(ore('stickTitanium') * 2 )
         .outputs(item('thermalfoundation:material', 514))
         .duration(200).EUt(240).buildAndRegister()

recipemap('assembler').recipeBuilder()
         .inputs(ore('wireFineGold') * 4 )
         .inputs(ore('dustRedstoneAlloy') * 12 )
         .fluidInputs(fluid('soldering_alloy') * 72 )
         .inputs(ore('foilSilver') * 12 )
         .inputs(ore('stickTitanium') * 2 )
         .outputs(item('thermalfoundation:material', 514))
         .duration(200).EUt(240).buildAndRegister()
// EV
recipemap('chemical_reactor').recipeBuilder()
        .inputs(ore('ingotSchrabidium') * 12)
        .inputs(item('hbm:powder_ice') * 4)
        .fluidInputs(fluid('iridium') * 120 )
        .fluidInputs(fluid('palladium') * 120 )
        .fluidOutputs(fluid('irschridium') * 270 )
        .duration(400).EUt(2048).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .inputs(ore('dustXenon135') * 12)
        .inputs(item('hbm:powder_ice') * 4)
        .fluidInputs(fluid('cryotheum') * 120 )
        .fluidInputs(fluid('coolant') * 120 )
        .fluidOutputs(fluid('supercoolant') * 270 )
        .duration(1200).EUt(2048).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .inputs(ore('dustAstralStarmetal') * 12)
        .notConsumable(item('hbm:gem_volcanic') * 4)
        .fluidInputs(fluid('watz') * 120 )
        .fluidInputs(fluid('liquid_death') * 120 )
        .fluidInputs(fluid('blaze') * 2400 )
        .outputs(item('thermalfoundation:material', 1024) * 4)
        .duration(400).EUt(2048).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .inputs(ore('dustTrinium') * 12)
        .notConsumable(item('hbm:gem_volcanic') * 4)
        .fluidInputs(fluid('watz') * 10000 )
        .fluidInputs(fluid('plasma_hd') * 120 )
        .fluidInputs(fluid('blaze') * 2400 )
        .outputs(item('thermalfoundation:material', 1024) * 2)
        .duration(400).EUt(2048).buildAndRegister()

recipemap('mixer').recipeBuilder()
        .inputs(ore('dustOsmium') * 6)
        .inputs(ore('dustPalladium') * 6)
        .inputs(ore('dustIridium') * 6)
        .outputs(item('gt_aurora:ultradense_powder'))
        .duration(400).EUt(2048).buildAndRegister()

// IV
recipemap('assembler').recipeBuilder()
         .inputs(ore('plateSiliconeRubber') * 4 )
         .fluidInputs(fluid('soldering_alloy') * 72 )
         .inputs(ore('plateOsmium') * 1 )
         .inputs(ore('componentDiode') * 2 )
         .outputs(item('appliedenergistics2:material', 52) * 16 )
         .duration(200).EUt(7500).buildAndRegister()

// ZPM

recipemap('assembler').recipeBuilder()
        .inputs(item('gregtech:meta_item_1', 386) * 3)
        .inputs(ore('plateCMBSteel') * 2)
        .inputs(ore('wireFineSchrabidium') * 2)
        .inputs(ore('dustNitanium') * 24)
        .inputs(ore('circuitUv'))
        .inputs(ore('screwDarmstadtium') * 2)
        .fluidInputs(fluid('polybenzimidazole') * 120)
        .outputs(item('gt_aurora:sparkschrabidic_epoxy_resin_sheet') * 2)
        .duration(200).EUt(60000).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .inputs(item('gt_aurora:sparkschrabidic_epoxy_resin_sheet') * 2)
        .fluidInputs(fluid('superschrabidium_board_reactant') * 120)
        .fluidInputs(fluid('supercoolant') * 20)
        .outputs(item('gt_aurora:sparkschrabidic_circuit_board') * 2)
        .duration(200).EUt(60000).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .inputs(ore('dustSodium') * 2)
        .fluidInputs(fluid('sas3') * 120)
        .fluidInputs(fluid('glycerol') * 20)
        .fluidOutputs(fluid('superschrabidium_board_reactant') * 120)
        .duration(200).EUt(60000).buildAndRegister()

// UV
recipemap('assembly_line').recipeBuilder()
        .stationResearch(b -> b.researchStack(item('gregtech:meta_item_1', 647)).CWUt(8))
        .inputs(item('gt_aurora:sparkschrabidic_circuit_board'))
        .inputs(ore('screwDarmstadtium') * 12)
        .inputs(ore('screwNaquadahAlloy') * 4)
        .inputs(item('gregtech:meta_item_1', 532) * 4)
        .inputs(item('gregtech:meta_item_1', 531) * 4)
        .inputs(item('gregtech:meta_item_1', 528) * 4)
        .inputs(ore('platePositronChargedEuroschidiumAlloy') * 12)
        .inputs(ore('wireFinePositronChargedEuroschidiumAlloy') * 6)
        .fluidInputs(fluid('schrabidium_based_sold_alloy') * 144 )
        .fluidInputs(fluid('polybenzimidazole') * 144 )
        .outputs(item('gt_aurora:hyperconducting_antischrabidic_circuit') * 12)
        .duration(800).EUt(524288).buildAndRegister()

recipemap('assembly_line').recipeBuilder()
        .stationResearch(b -> b.researchStack(item('hbm:capsule_sing_tiny')).CWUt(4))
        .inputs(item('gt_aurora:sparkschrabidic_circuit_board') * 2)
        .inputs(ore('screwNaquadahAlloy') * 6)
        .inputs(ore('plateAmericium') * 4)
        .inputs(item('gregtech:meta_item_1', 532) * 2)
        .inputs(item('gregtech:meta_item_1', 531) * 2)
        .inputs(ore('plateIrschidium') * 12)
        .inputs(ore('wireFineTrinium') * 6)
        .fluidInputs(fluid('schrabidium_based_sold_alloy') * 144 )
        .fluidInputs(fluid('polybenzimidazole') * 144 )
        .outputs(item('gt_aurora:hyperconducting_antischrabidic_assembly') * 12)
        .duration(800).EUt(524288).buildAndRegister()

// UHV
recipemap('chemical_reactor').recipeBuilder()
        .inputs(ore('ingotEuropium') * 6)
        .fluidInputs(fluid('amat') * 120 )
        .fluidInputs(fluid('aschrab') * 120 )
        .fluidOutputs(fluid('positron_charged_euroschidium_alloy') * 120 )
        .duration(400).EUt(620000).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .inputs(ore('itemBinderComposite') * 12)
        .fluidInputs(fluid('sas3') * 120 )
        .fluidInputs(fluid('soldering_alloy') * 120 )
        .fluidInputs(fluid('darmstadtium') * 150 )
        .fluidOutputs(fluid('schrabidium_based_sold_alloy') * 250 )
        .duration(400).EUt(600000).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
        .inputs(item('gregtech:meta_ingot', 32003) * 2 )
        .fluidInputs(fluid('aschrab') * 250 )
        .outputs(item('gregtech:meta_ingot', 32012) * 2 )
        .duration(400).EUt(2097152).buildAndRegister()


recipemap('chemical_reactor').recipeBuilder()
        .inputs(ore('ingotNeutronium') * 12)
        .fluidInputs(fluid('sas3') * 120 )
        .fluidInputs(fluid('amat') * 120 )
        .fluidInputs(fluid('darmstadtium') * 150 )
        .fluidOutputs(fluid('antineutronium') * 270 )
        .duration(400).EUt(620000).buildAndRegister()



recipemap('assembly_line').recipeBuilder()
        .stationResearch(b -> b.researchStack(item('hbm:ams_core_sing', 647)).CWUt(12))
        .inputs(ore('screwNeutronium') * 64)
        .inputs(ore('screwAntineutronium') * 64)
        .inputs(item('gregtech:meta_item_1', 532) * 64)
        .inputs(item('gregtech:meta_item_1', 531) * 64)
        .inputs(item('gregtech:meta_item_1', 528) * 64)
        .inputs(item('gregtech:meta_item_1', 528) * 64)
        .notConsumable(item('hbm:laser_crystal_digamma'))
        .inputs(item('gt_aurora:sparkschrabidic_circuit_board'))
        .inputs(ore('platePositronChargedAntineutronium') * 64)
        .inputs(ore('wireFinePositronChargedEuroschidiumAlloy') * 64)
        .inputs(ore('wireFinePositronChargedEuroschidiumAlloy') * 64)
        .inputs(ore('wireFinePositronChargedEuroschidiumAlloy') * 64)
        .inputs(ore('wireFinePositronChargedEuroschidiumAlloy') * 64)
        .fluidInputs(fluid('schrabidium_based_sold_alloy') * 144 )
        .fluidInputs(fluid('aschrab') * 144 )
        .fluidInputs(fluid('amat') * 144 )
        .outputs(item('gt_aurora:hyperconducting_antischrabidic_mainframe'))
        .duration(800).EUt(2097152).buildAndRegister()

recipemap('mixer').recipeBuilder()
        .inputs(ore('dustStellite100'))
        .inputs(ore('dustSaturnite'))
        .inputs(ore('dustSchrabidium'))
        .outputs(metaitem('dustStarmetal'))
        .duration(400).EUt(2048).buildAndRegister()


recipemap('mixer').recipeBuilder()
        .inputs(ore('dustStellite100'))
        .inputs(ore('dustSaturnite'))
        .inputs(ore('dustSchrabidium'))
        .outputs(metaitem('dustStarmetal'))
        .duration(400).EUt(2048).buildAndRegister()


recipemap('assembler').recipeBuilder()
         .inputs(ore('wireFineElectrum') * 4 )
         .inputs(ore('dustElectrotineAlloy') * 12 )
         .fluidInputs(fluid('soldering_alloy') * 72 )
         .inputs(ore('foilGold') * 12 )
         .inputs(ore('stickSteel') * 2 )
         .outputs(item('thermalfoundation:material', 513))
         .duration(200).EUt(240).buildAndRegister()

recipemap('assembler').recipeBuilder()
         .inputs(ore('wireFineTantalum') * 4 )
         .inputs(ore('dustAdvancedAlloy') * 12 )
         .fluidInputs(fluid('soldering_alloy') * 72 )
         .inputs(ore('foilCopper') * 12 )
         .inputs(ore('stickSteel') * 2 )
         .outputs(item('thermalfoundation:material', 515))
         .duration(200).EUt(240).buildAndRegister()/