mods.bloodmagic.alchemy_array.recipeBuilder()
    .input(item('bloodmagic:activation_crystal'))
    .catalyst(item('bloodmagic:slate:2'))
    .output(item('astralsorcery:itemwand'))
    .texture('bloodmagic:textures/models/AlchemyArrays/LightSigil.png')
    .register()

mods.bloodmagic.blood_altar.recipeBuilder()
    .input(ore('ingotThaumium'))
    .output(item('gregtech:meta_ingot', 32004))
    .minimumTier(2)
    .drainRate(5)
    .syphon(1000)
    .consumeRate(20)
    .register()